default_language_version:
  python: python3.10

exclude: ^(\.[^/]*cache/.*)|(poetry.lock)$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
      - id: check-builtin-literals
      - id: check-ast
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-toml

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.36.2
    hooks:
      - id: yamllint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--toml, pyproject.toml]
        additional_dependencies:
          - tomli


  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml', '-ll', '-q']
        additional_dependencies: ['bandit[toml]']

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
