name: fishtools
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - anndata>=0.12.0
  - zarr>=3
  - astropy
  - bowtie2
  - click
  - colorama
  - cupy
  - htslib
  - imagecodecs
  - kmer-jellyfish
  - levenshtein
  - loguru
  - matplotlib
  - numpy<2
  - opencv
  - pandas
  - pip
  - pip:
      - basicpy
      - biopython
      - cmocean
      - colorcet
      - hyperactive<5
      - kb-python
      - itk
      - line_profiler
      - primer3-py
      - pyfastx
      - simpleitk
      - spaco-release
  - polars
  - prefect
  - pyarrow
  - pydantic
  - pyfiglet
  - repeatmasker
  - rich-click
  - rtree
  - samtools
  - scanpy
  - shapely
  - toml
