name: fishtools
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - astropy
  - bowtie2
  - click
  - colorama
  - cupy
  - imagecodecs
  - kmer-jellyfish
  - levenshtein
  - loguru
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pip
  - pip:
      - basicpy
      - biopython
      - kb-python
      - primer3-py
      - pyfastx
  - polars
  - pyarrow
  - pydantic
  - repeatmasker
  - rich-click
  - rtree
  - scanpy
  - shapely
  - toml
