# %% [markdown]
# # 3D cortex mid-surface overlay viewers (DevCCF E15.5)
#
# Interactive slice viewers (coronal and sagittal) for artifacts generated by:
# `ccf/refextract/midsurface_neocortex_mesocortex_allocortex_ccf_3d.py`
#
# Run cells sequentially. Two Matplotlib slider viewers will open:
# - coronal viewer: slice i (axis 0), showing x=k, y=j
# - sagittal viewer: slice k (axis 2), showing x=j, y=i

# %%
from __future__ import annotations

import csv
import os
from pathlib import Path

import matplotlib
matplotlib.rcParams.update(matplotlib.rcParamsDefault)

import matplotlib.pyplot as plt
import numpy as np
from IPython import get_ipython
from matplotlib.collections import LineCollection
from matplotlib.colors import Normalize
from matplotlib.widgets import Slider
from scipy.ndimage import distance_transform_edt

# Optional: VS Code interactive Matplotlib backend
ip = get_ipython()
if ip is not None:
    ip.run_line_magic("matplotlib", "widget")

# %% [markdown]
# ## Configuration

# %%
# === EDIT THESE ===

ATLAS_NAME = "kim_dev_mouse_e15-5_lsfm_20um"
OUTDIR = Path("/home/chaichontat/fishtools2/ccf/out/refextract/midsurface_neocortex_mesocortex_allocortex_3d")
BRAINGLOBE_CONFIG_DIR = Path("ccf/out/atlases/.brainglobe_config")

KEEP_LEFT_HEMISPHERE_ONLY = True
DS = 1

SHOW_FIGURES = True
CONTOUR_LEVEL = 0.5
CONTOUR_COLOR = "#d62728"
U_CURVE_T_CMAP = "viridis"
MASK_COLOR = "#2ca02c"
MASK_ALPHA = 0.18
OVERLAY_NEO_MESO_COLOR = "#ff0000"
OVERLAY_NEO_MESO_ALPHA = 0.0
BOUNDARY_ALPHA = 0.85
SLIDER_DEBOUNCE_MS = 40
MANUAL_CONNECT_CORONAL_PATH_TEMPLATE = "manual_coronal_midcurve_override_slice{slice_i}_yx.npy"
MANUAL_CONNECT_SAGITTAL_PATH_TEMPLATE = "manual_sagittal_midcurve_override_slice{slice_k}_yx.npy"

SHOW_R_OVERLAY = False
R_CLIP_UM = 800.0

SHOW_T_FIELD = True
T_FIELD_ALPHA = 0.45
T_FIELD_CMAP = "viridis"

OUTDIR.mkdir(parents=True, exist_ok=True)


# %% [markdown]
# ## Helpers

# %%
def _resolution_ijk_um(res: object) -> tuple[float, float, float]:
    if isinstance(res, (int, float)):
        r = float(res)
        return (r, r, r)
    if isinstance(res, (tuple, list)) and len(res) == 3 and all(isinstance(v, (int, float)) for v in res):
        return (float(res[0]), float(res[1]), float(res[2]))
    raise ValueError(f"Unsupported atlas.resolution: {res!r}")


def _robust_vmin_vmax(vol_3d: np.ndarray) -> tuple[float, float]:
    sample = vol_3d[::4, ::4, ::4].astype(np.float32, copy=False)
    vmin, vmax = np.percentile(sample, [1, 99]).astype(np.float64)
    if not np.isfinite(vmin) or not np.isfinite(vmax) or float(vmax) <= float(vmin):
        vmin = float(np.nanmin(sample))
        vmax = float(np.nanmax(sample))
        if not np.isfinite(vmin) or not np.isfinite(vmax) or float(vmax) <= float(vmin):
            vmin, vmax = 0.0, 1.0
    return float(vmin), float(vmax)


def _masked_u_slice(u2: np.ndarray, mask2: np.ndarray) -> np.ndarray:
    u2 = u2.astype(np.float32, copy=False)
    mask2 = mask2.astype(bool, copy=False)
    out = np.full(u2.shape, np.nan, dtype=np.float32)
    out[mask2] = u2[mask2]
    return out


def _binary_overlay_slice(mask2: np.ndarray) -> np.ndarray:
    """Return float image with NaN outside mask so imshow can keep background transparent."""
    m = np.asarray(mask2, dtype=bool)
    out = np.full(m.shape, np.nan, dtype=np.float32)
    out[m] = 1.0
    return out


def _normalized_arc_t_for_path_xy(path_xy: np.ndarray) -> np.ndarray:
    pts = np.asarray(path_xy, dtype=np.float64)
    if pts.ndim != 2 or pts.shape[0] < 2 or pts.shape[1] != 2:
        raise ValueError(f"Expected path_xy shape (N,2), got {pts.shape}.")
    if not np.isfinite(pts).all():
        raise ValueError("path_xy must be finite.")
    d = np.diff(pts, axis=0)
    seg = np.sqrt(np.sum(d * d, axis=1))
    s = np.concatenate([np.zeros((1,), dtype=np.float64), np.cumsum(seg, dtype=np.float64)])
    total = float(s[-1])
    if not np.isfinite(total) or total <= 0.0:
        return np.linspace(0.0, 1.0, pts.shape[0], dtype=np.float32)
    return (s / total).astype(np.float32, copy=False)


def _t_field_from_path(*, mask_yx: np.ndarray, path_xy: np.ndarray, t_vertices: np.ndarray) -> np.ndarray:
    """Rasterize (path_xy, t_vertices) and diffuse nearest-path t across mask_yx."""
    mask = np.asarray(mask_yx, dtype=bool)
    h, w = mask.shape
    pts = np.asarray(path_xy, dtype=np.float64)
    t = np.asarray(t_vertices, dtype=np.float64)
    if pts.ndim != 2 or pts.shape[0] < 2 or pts.shape[1] != 2:
        raise ValueError(f"Expected path_xy shape (N,2), got {pts.shape}.")
    if t.ndim != 1 or t.shape[0] != pts.shape[0]:
        raise ValueError(f"Expected t_vertices shape ({pts.shape[0]},), got {t.shape}.")
    finite = np.isfinite(pts[:, 0]) & np.isfinite(pts[:, 1]) & np.isfinite(t)
    if int(np.count_nonzero(finite)) < 2:
        out = np.full((h, w), np.nan, dtype=np.float32)
        out[~mask] = np.nan
        return out
    pts = pts[finite]
    t = t[finite]

    xs: list[np.ndarray] = []
    ys: list[np.ndarray] = []
    ts: list[np.ndarray] = []
    for i in range(int(pts.shape[0]) - 1):
        x0, y0 = float(pts[i, 0]), float(pts[i, 1])
        x1, y1 = float(pts[i + 1, 0]), float(pts[i + 1, 1])
        t0, t1 = float(t[i]), float(t[i + 1])
        n = int(np.ceil(max(abs(x1 - x0), abs(y1 - y0), 1.0))) + 1
        xs.append(np.linspace(x0, x1, n, dtype=np.float64))
        ys.append(np.linspace(y0, y1, n, dtype=np.float64))
        ts.append(np.linspace(t0, t1, n, dtype=np.float64))

    x = np.concatenate(xs) if xs else pts[:, 0]
    y = np.concatenate(ys) if ys else pts[:, 1]
    tv = np.concatenate(ts) if ts else t
    xi = np.clip(np.rint(x).astype(np.int64, copy=False), 0, w - 1)
    yi = np.clip(np.rint(y).astype(np.int64, copy=False), 0, h - 1)
    flat = yi * w + xi

    uniq, inv = np.unique(flat, return_inverse=True)
    sums = np.bincount(inv, weights=tv, minlength=int(uniq.size)).astype(np.float64, copy=False)
    counts = np.bincount(inv, minlength=int(uniq.size)).astype(np.float64, copy=False)
    mean_t = np.divide(sums, counts, out=np.full_like(sums, np.nan, dtype=np.float64), where=counts > 0.0)

    seed_t = np.full((h, w), np.nan, dtype=np.float32)
    seed_t[(uniq // w).astype(np.int64, copy=False), (uniq % w).astype(np.int64, copy=False)] = mean_t.astype(np.float32, copy=False)
    seed_mask = np.isfinite(seed_t)
    if int(np.count_nonzero(seed_mask)) < 2:
        out = np.full((h, w), np.nan, dtype=np.float32)
        out[~mask] = np.nan
        return out

    _, (iy, ix) = distance_transform_edt(~seed_mask, return_indices=True)
    out = seed_t[iy, ix].astype(np.float32, copy=False)
    out[~mask] = np.nan
    return out


def _load_manual_override_paths(outdir: Path, *, axis: str) -> dict[int, np.ndarray]:
    if axis == "coronal":
        prefix = "manual_coronal_midcurve_override_slice"
        pattern = MANUAL_CONNECT_CORONAL_PATH_TEMPLATE.format(slice_i="*")
    elif axis == "sagittal":
        prefix = "manual_sagittal_midcurve_override_slice"
        pattern = MANUAL_CONNECT_SAGITTAL_PATH_TEMPLATE.format(slice_k="*")
    else:
        raise ValueError(f"Unsupported axis={axis!r}")

    out: dict[int, np.ndarray] = {}
    for path in sorted(outdir.glob(pattern)):
        stem = path.stem
        if not stem.startswith(prefix):
            continue
        tail = stem[len(prefix) :]
        if tail.endswith("_yx"):
            tail = tail[: -len("_yx")]
        if not tail.isdigit():
            continue
        arr = np.load(path).astype(np.float32, copy=False)
        if arr.ndim != 2 or arr.shape[1] != 2 or arr.shape[0] < 2:
            continue
        out[int(tail)] = arr
    return out


def _clear_contours(cont: object | None) -> None:
    if cont is None:
        return
    collections = getattr(cont, "collections", None)
    if collections is None:
        return
    for c in list(collections):
        try:
            c.remove()
        except Exception:
            pass


def _clear_artist(artist: object | None) -> None:
    if artist is None:
        return
    remove = getattr(artist, "remove", None)
    if callable(remove):
        remove()


def _plot_parametrized_curve(
    ax: plt.Axes,
    contour_segments: list[np.ndarray],
    *,
    cmap: str,
    norm: Normalize,
    linewidth: float,
    alpha: float,
    zorder: float,
    t_vertices_by_segment: list[np.ndarray] | None = None,
) -> LineCollection | None:
    segments: list[np.ndarray] = []
    t_values: list[np.ndarray] = []
    for seg_idx, path_xy in enumerate(contour_segments):
        path_xy = np.asarray(path_xy, dtype=np.float32)
        if path_xy.ndim != 2 or path_xy.shape[0] < 2 or path_xy.shape[1] != 2:
            continue
        if t_vertices_by_segment is None or seg_idx >= len(t_vertices_by_segment):
            t_vertices = np.linspace(0.0, 1.0, path_xy.shape[0], dtype=np.float32)
        else:
            t_vertices = np.asarray(t_vertices_by_segment[seg_idx], dtype=np.float32)
            if t_vertices.ndim != 1 or t_vertices.shape[0] != path_xy.shape[0] or not np.isfinite(t_vertices).all():
                t_vertices = np.linspace(0.0, 1.0, path_xy.shape[0], dtype=np.float32)
        segments.append(np.stack([path_xy[:-1], path_xy[1:]], axis=1))
        t_values.append(0.5 * (t_vertices[:-1] + t_vertices[1:]))
    if not segments:
        return None

    lc = LineCollection(
        np.concatenate(segments, axis=0),
        cmap=cmap,
        norm=norm,
        linewidths=linewidth,
        alpha=alpha,
        zorder=zorder,
    )
    lc.set_array(np.concatenate(t_values, axis=0))
    ax.add_collection(lc)
    return lc


def _polyline_length_xy(path_xy: np.ndarray) -> float:
    pts = np.asarray(path_xy, dtype=np.float64)
    if pts.ndim != 2 or pts.shape[0] < 2 or pts.shape[1] != 2:
        return 0.0
    d = np.diff(pts, axis=0)
    return float(np.sum(np.sqrt(np.sum(d * d, axis=1))))


def _point_on_polyline_xy(path_xy: np.ndarray, t: float) -> np.ndarray | None:
    pts = np.asarray(path_xy, dtype=np.float64)
    if pts.ndim != 2 or pts.shape[0] < 2 or pts.shape[1] != 2:
        return None
    t_clip = float(np.clip(float(t), 0.0, 1.0))
    seg = np.sqrt(np.sum(np.diff(pts, axis=0) ** 2, axis=1))
    s = np.concatenate([np.zeros((1,), dtype=np.float64), np.cumsum(seg, dtype=np.float64)])
    total = float(s[-1])
    if not np.isfinite(total) or total <= 0.0:
        return pts[0].astype(np.float64, copy=False)
    q = t_clip * total
    x = np.interp(q, s, pts[:, 0])
    y = np.interp(q, s, pts[:, 1])
    return np.asarray([x, y], dtype=np.float64)


def _point_on_path_xy_by_t(path_xy: np.ndarray, t_vertices: np.ndarray, t_query: float) -> np.ndarray | None:
    pts = np.asarray(path_xy, dtype=np.float64)
    t_vals = np.asarray(t_vertices, dtype=np.float64)
    if pts.ndim != 2 or pts.shape[0] < 2 or pts.shape[1] != 2:
        return None
    if t_vals.ndim != 1 or t_vals.shape[0] != pts.shape[0]:
        return None
    finite = np.isfinite(t_vals) & np.isfinite(pts[:, 0]) & np.isfinite(pts[:, 1])
    if int(np.count_nonzero(finite)) < 2:
        return None
    t_f = t_vals[finite]
    p_f = pts[finite]
    order = np.argsort(t_f)
    t_f = t_f[order]
    p_f = p_f[order]
    t_unique, uniq_idx = np.unique(t_f, return_index=True)
    if t_unique.size < 2:
        return None
    p_unique = p_f[uniq_idx]
    x = np.interp(float(t_query), t_unique, p_unique[:, 0], left=np.nan, right=np.nan)
    y = np.interp(float(t_query), t_unique, p_unique[:, 1], left=np.nan, right=np.nan)
    if not np.isfinite(x) or not np.isfinite(y):
        return None
    return np.asarray([x, y], dtype=np.float64)


def _t_extent_on_path_t_for_mask(path_xy: np.ndarray, t_vertices: np.ndarray, mask_yx: np.ndarray) -> tuple[float, float] | None:
    pts = np.asarray(path_xy, dtype=np.float64)
    t_vals = np.asarray(t_vertices, dtype=np.float64)
    mask = np.asarray(mask_yx, dtype=bool)
    if pts.ndim != 2 or pts.shape[0] < 2 or pts.shape[1] != 2:
        return None
    if t_vals.ndim != 1 or t_vals.shape[0] != pts.shape[0]:
        return None
    if mask.ndim != 2:
        return None
    h, w = mask.shape
    xi = np.clip(np.rint(pts[:, 0]).astype(np.int64, copy=False), 0, w - 1)
    yi = np.clip(np.rint(pts[:, 1]).astype(np.int64, copy=False), 0, h - 1)
    inside = mask[yi, xi]
    if not np.any(inside):
        return None
    t_in = t_vals[inside]
    finite = np.isfinite(t_in)
    if int(np.count_nonzero(finite)) < 2:
        return None
    return (float(np.min(t_in[finite])), float(np.max(t_in[finite])))


def _load_overlap_t_ranges_csv(path: Path, *, slice_label: str) -> dict[int, list[tuple[float, float]]]:
    """Load slice-local overlap ranges (`t_all`) from `*_overlap_t_ranges.csv`."""
    out: dict[int, list[tuple[float, float]]] = {}
    if not path.exists():
        return out
    with path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames or []
        has_t_all = ("t_start_all" in fieldnames) and ("t_end_all" in fieldnames)
        has_t = ("t_start" in fieldnames) and ("t_end" in fieldnames)
        if has_t_all:
            t_start_key = "t_start_all"
            t_end_key = "t_end_all"
        elif has_t:
            t_start_key = "t_start"
            t_end_key = "t_end"
        else:
            raise ValueError(
                f"{path} must contain either ('t_start_all', 't_end_all') or ('t_start', 't_end'). "
                "Regenerate artifacts with midsurface_neocortex_mesocortex_allocortex_ccf_3d.py."
            )
        for row in reader:
            if slice_label not in row or t_start_key not in row or t_end_key not in row:
                continue
            raw_slice = row[slice_label]
            if raw_slice is None:
                continue
            slice_val = float(raw_slice)
            if not np.isfinite(slice_val):
                continue
            slice_idx = int(np.rint(slice_val))
            t0 = float(row[t_start_key])
            t1 = float(row[t_end_key])
            if not np.isfinite(t0) or not np.isfinite(t1):
                continue
            out.setdefault(slice_idx, []).append((t0, t1))
    for slice_idx in out:
        out[slice_idx].sort(key=lambda x: x[0])
    return out


def _load_midline_paths_csv(path: Path, *, slice_label: str) -> dict[int, tuple[np.ndarray, np.ndarray]]:
    out: dict[int, tuple[np.ndarray, np.ndarray]] = {}
    if not path.exists():
        return out

    grouped: dict[int, list[tuple[float, float, float]]] = {}
    with path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if slice_label not in row or "t" not in row or "y" not in row or "x" not in row:
                continue
            raw_slice = row[slice_label]
            if raw_slice is None:
                continue
            slice_val = float(raw_slice)
            if not np.isfinite(slice_val):
                continue
            slice_idx = int(np.rint(slice_val))
            t = float(row["t"])
            y = float(row["y"])
            x = float(row["x"])
            if not np.isfinite(t) or not np.isfinite(y) or not np.isfinite(x):
                continue
            grouped.setdefault(slice_idx, []).append((t, x, y))

    for slice_idx, vals in grouped.items():
        if len(vals) < 2:
            continue
        vals_sorted = sorted(vals, key=lambda v: v[0])
        t_vals = np.asarray([vt for vt, _, _ in vals_sorted], dtype=np.float32)
        path_xy = np.asarray([[vx, vy] for _, vx, vy in vals_sorted], dtype=np.float32)
        if path_xy.ndim != 2 or path_xy.shape[0] < 2 or path_xy.shape[1] != 2:
            continue
        if t_vals.ndim != 1 or t_vals.shape[0] != path_xy.shape[0]:
            continue
        out[int(slice_idx)] = (path_xy, t_vals)
    return out


def _midline_t_limits(paths: dict[int, tuple[np.ndarray, np.ndarray]]) -> tuple[float, float]:
    vals: list[np.ndarray] = []
    for _slice_idx, (_path_xy, t_vals) in paths.items():
        t = np.asarray(t_vals, dtype=np.float64)
        t = t[np.isfinite(t)]
        if t.size > 0:
            vals.append(t)
    if not vals:
        return (0.0, 1.0)
    all_t = np.concatenate(vals)
    vmin = float(np.nanpercentile(all_t, 1.0))
    vmax = float(np.nanpercentile(all_t, 99.0))
    if not np.isfinite(vmin) or not np.isfinite(vmax) or vmax <= vmin:
        vmin = float(np.nanmin(all_t))
        vmax = float(np.nanmax(all_t))
    vmin = min(vmin, 0.0)
    vmax = max(vmax, 1.0)
    if not np.isfinite(vmin) or not np.isfinite(vmax) or vmax <= vmin:
        return (0.0, 1.0)
    return (vmin, vmax)


def _format_t_ranges(ranges: list[tuple[float, float]]) -> str:
    if not ranges:
        return "none"
    return "; ".join([f"{float(t0):.3f}-{float(t1):.3f}" for t0, t1 in ranges])


# %% [markdown]
# ## Phase 0: Load atlas reference

# %%
if BRAINGLOBE_CONFIG_DIR.exists():
    os.environ["BRAINGLOBE_CONFIG_DIR"] = str(BRAINGLOBE_CONFIG_DIR.resolve())

from brainglobe_atlasapi import BrainGlobeAtlas  # noqa: E402

atlas = BrainGlobeAtlas(ATLAS_NAME)
RES_I_UM, RES_J_UM, RES_K_UM = _resolution_ijk_um(atlas.resolution)
print(f"ATLAS_NAME={ATLAS_NAME!r}")
print(f"atlas.resolution={atlas.resolution!r} (um)")

reference_3d = np.asarray(atlas.reference)
reference_3d = reference_3d[::DS, ::DS, ::DS]
if KEEP_LEFT_HEMISPHERE_ONLY:
    reference_3d = reference_3d[:, :, : reference_3d.shape[2] // 2]
print(f"reference_3d (downsampled) shape={reference_3d.shape} dtype={reference_3d.dtype}")


# %% [markdown]
# ## Phase 1: Load midsurface artifacts

# %%
req = {
    "cortex_fit": OUTDIR / "cortex_mask_fit_3d_ds.npy",
    "cortex_clean": OUTDIR / "cortex_mask_clean_3d_ds.npy",
    "neo_meso_overlay": OUTDIR / "overlay_neocortex_mesocortex_no_allocortex_3d_ds.npy",
    "u_halfway": OUTDIR / "halfway_u_3d_ds.npy",
    "b0": OUTDIR / "laplace_b0_pial_3d_ds.npy",
    "b1": OUTDIR / "laplace_b1_inner_3d_ds.npy",
    "r_um": OUTDIR / "halfway_r_um_crop.npy",
    "crop_origin": OUTDIR / "halfway_crop_origin_ijk.npy",
    "midline_include": OUTDIR / "midline_include_neo_meso_3d_ds.npy",
    "coronal_midline_columns": OUTDIR / "coronal_midline_columns.csv",
    "sagittal_midline_columns": OUTDIR / "sagittal_midline_columns.csv",
    "coronal_t_ranges": OUTDIR / "coronal_neocortex_mesocortex_overlap_t_ranges.csv",
    "sagittal_t_ranges": OUTDIR / "sagittal_neocortex_mesocortex_overlap_t_ranges.csv",
}
missing = [name for name in ["b0", "b1"] if not req[name].exists()]
if missing or (not req["cortex_fit"].exists() and not req["cortex_clean"].exists()) or (not req["u_halfway"].exists()):
    raise FileNotFoundError(
        f"Missing artifacts in {OUTDIR}: {missing}. Run midsurface_neocortex_mesocortex_allocortex_ccf_3d.py first."
    )

mask_path = req["cortex_fit"] if req["cortex_fit"].exists() else req["cortex_clean"]
cortex_3d = np.load(mask_path).astype(bool)
u_path = req["u_halfway"]
u_3d = np.load(req["u_halfway"]).astype(np.float32, copy=False)
b0_3d = np.load(req["b0"]).astype(bool)
b1_3d = np.load(req["b1"]).astype(bool)
print(f"Loaded cortex mask: {mask_path}")
print(f"Loaded u field: {u_path}")

midline_include_3d: np.ndarray | None = None
if req["midline_include"].exists():
    midline_include_3d = np.load(req["midline_include"]).astype(bool)
    if midline_include_3d.shape != cortex_3d.shape:
        raise ValueError(
            f"midline_include shape mismatch: {midline_include_3d.shape} vs cortex {cortex_3d.shape} (check DS)."
        )
    print(f"Loaded midline include mask: {req['midline_include']}")

overlay_neo_meso_no_allocortex_3d: np.ndarray | None = None
if req["neo_meso_overlay"].exists():
    overlay_neo_meso_no_allocortex_3d = np.load(req["neo_meso_overlay"]).astype(bool)
    if overlay_neo_meso_no_allocortex_3d.shape != cortex_3d.shape:
        raise ValueError(
            "neocortex+mesocortex overlay shape mismatch: "
            f"{overlay_neo_meso_no_allocortex_3d.shape} vs cortex {cortex_3d.shape} (check DS)."
        )
    print(f"Loaded neocortex+mesocortex overlay mask: {req['neo_meso_overlay']}")

r_um_crop: np.ndarray | None = None
crop_origin: np.ndarray | None = None
if bool(SHOW_R_OVERLAY):
    if not req["r_um"].exists() or not req["crop_origin"].exists():
        raise FileNotFoundError(f"SHOW_R_OVERLAY=True but missing {req['r_um'].name} or {req['crop_origin'].name}")
    r_um_crop = np.load(req["r_um"]).astype(np.float32, copy=False)
    crop_origin = np.load(req["crop_origin"]).astype(np.int32, copy=False)
    if crop_origin.shape != (3,):
        raise ValueError(f"Expected crop_origin shape (3,), got {crop_origin.shape}")
    print(f"Loaded r field: {req['r_um']}")

if KEEP_LEFT_HEMISPHERE_ONLY:
    # Reference is already halved; make sure overlays match.
    kmax = cortex_3d.shape[2]
    reference_3d = reference_3d[:, :, :kmax]

if reference_3d.shape != cortex_3d.shape or cortex_3d.shape != u_3d.shape:
    raise ValueError(
        f"Shape mismatch: reference={reference_3d.shape} cortex={cortex_3d.shape} u={u_3d.shape}. "
        f"Check DS and KEEP_LEFT_HEMISPHERE_ONLY."
    )

vmin, vmax = _robust_vmin_vmax(reference_3d)
manual_coronal_paths = _load_manual_override_paths(OUTDIR, axis="coronal")
manual_sagittal_paths = _load_manual_override_paths(OUTDIR, axis="sagittal")
coronal_midline_paths = _load_midline_paths_csv(req["coronal_midline_columns"], slice_label="slice_i")
sagittal_midline_paths = _load_midline_paths_csv(req["sagittal_midline_columns"], slice_label="slice_k")
coronal_t_vmin, coronal_t_vmax = _midline_t_limits(coronal_midline_paths)
sagittal_t_vmin, sagittal_t_vmax = _midline_t_limits(sagittal_midline_paths)
if manual_coronal_paths:
    print(f"Loaded {len(manual_coronal_paths)} coronal manual override paths from {OUTDIR}")
if manual_sagittal_paths:
    print(f"Loaded {len(manual_sagittal_paths)} sagittal manual override paths from {OUTDIR}")
if coronal_midline_paths:
    print(f"Loaded {len(coronal_midline_paths)} coronal midline paths from {req['coronal_midline_columns']}")
if sagittal_midline_paths:
    print(f"Loaded {len(sagittal_midline_paths)} sagittal midline paths from {req['sagittal_midline_columns']}")
print(
    "Midline t ranges for display: "
    f"coronal=[{coronal_t_vmin:.3f},{coronal_t_vmax:.3f}] "
    f"sagittal=[{sagittal_t_vmin:.3f},{sagittal_t_vmax:.3f}]"
)
coronal_overlap_t_ranges = _load_overlap_t_ranges_csv(req["coronal_t_ranges"], slice_label="slice_i")
sagittal_overlap_t_ranges = _load_overlap_t_ranges_csv(req["sagittal_t_ranges"], slice_label="slice_k")
if coronal_overlap_t_ranges:
    print(f"Loaded coronal neocortex+mesocortex t-ranges for {len(coronal_overlap_t_ranges)} slices.")
if sagittal_overlap_t_ranges:
    print(f"Loaded sagittal neocortex+mesocortex t-ranges for {len(sagittal_overlap_t_ranges)} slices.")


# %% [markdown]
# ## Phase 2: Coronal viewer (slice i)

# %%
def view_coronal_overlay(*, show: bool = True) -> None:
    n_i = int(reference_3d.shape[0])
    cur_i = int(np.clip(int(np.nanmedian(np.where(cortex_3d.any(axis=(1, 2)))[0])), 0, n_i - 1))

    fig, ax = plt.subplots(figsize=(7.7, 7.7))
    plt.subplots_adjust(bottom=0.14)
    t_field_cache: dict[int, np.ndarray] = {}

    img = ax.imshow(
        reference_3d[cur_i, :, :],
        cmap="gray",
        interpolation="nearest",
        vmin=vmin,
        vmax=vmax,
        origin="upper",
    )
    mask_im = ax.imshow(
        _binary_overlay_slice(cortex_3d[cur_i, :, :]),
        cmap=plt.cm.colors.ListedColormap([MASK_COLOR]),
        interpolation="nearest",
        alpha=MASK_ALPHA,
        origin="upper",
        zorder=2,
    )
    mask_im.cmap.set_bad(alpha=0.0)
    overlay_im = None
    if overlay_neo_meso_no_allocortex_3d is not None:
        overlay_im = ax.imshow(
            _binary_overlay_slice(overlay_neo_meso_no_allocortex_3d[cur_i, :, :]),
            cmap=plt.cm.colors.ListedColormap([OVERLAY_NEO_MESO_COLOR]),
            interpolation="nearest",
            alpha=float(OVERLAY_NEO_MESO_ALPHA),
            origin="upper",
            zorder=2.2,
        )
        overlay_im.cmap.set_bad(alpha=0.0)
    t_im = None
    r_im = None
    if bool(SHOW_R_OVERLAY):
        cmap_r = plt.get_cmap("coolwarm").copy()
        cmap_r.set_bad(alpha=0.0)
        r_im = ax.imshow(
            np.full_like(reference_3d[cur_i, :, :], np.nan, dtype=np.float32),
            cmap=cmap_r,
            interpolation="nearest",
            origin="upper",
            vmin=-float(R_CLIP_UM),
            vmax=float(R_CLIP_UM),
            alpha=0.55,
            zorder=2.5,
        )

    curve_lc: LineCollection | None = None
    sc_t_start = ax.scatter([], [], s=88.0, c="#ffff00", marker="*", edgecolors="k", linewidths=0.45, zorder=4.5)
    sc_t_end = ax.scatter([], [], s=88.0, c="#ff0000", marker="*", edgecolors="k", linewidths=0.45, zorder=4.5)
    sc_b0 = ax.scatter([], [], s=3.0, c="#1f77b4", alpha=0.7, linewidths=0.0, zorder=4, label="pial seed")
    sc_b1 = ax.scatter([], [], s=3.0, c="#ff7f0e", alpha=0.7, linewidths=0.0, zorder=4, label="inner seed")
    curve_norm = Normalize(vmin=float(coronal_t_vmin), vmax=float(coronal_t_vmax))
    curve_sm = plt.cm.ScalarMappable(norm=curve_norm, cmap=U_CURVE_T_CMAP)
    curve_sm.set_array(np.array([curve_norm.vmin, curve_norm.vmax], dtype=np.float32))
    fig.colorbar(curve_sm, ax=ax, fraction=0.046, pad=0.02, label="t_all")
    if bool(SHOW_T_FIELD):
        cmap_t = plt.get_cmap(T_FIELD_CMAP).copy()
        cmap_t.set_bad(alpha=0.0)
        t_im = ax.imshow(
            np.full_like(reference_3d[cur_i, :, :], np.nan, dtype=np.float32),
            cmap=cmap_t,
            norm=curve_norm,
            interpolation="nearest",
            origin="upper",
            alpha=float(T_FIELD_ALPHA),
            zorder=2.35,
        )

    ax.set_xlabel("k (x)")
    ax.set_ylabel("j (y)")

    slider_ax = fig.add_axes((0.15, 0.06, 0.7, 0.03))
    slider = Slider(slider_ax, "slice i", 0, n_i - 1, valinit=cur_i, valstep=1)

    def set_i(i: int) -> None:
        nonlocal curve_lc
        i = int(np.clip(int(i), 0, n_i - 1))
        img.set_data(reference_3d[i, :, :])
        mask_im.set_data(_binary_overlay_slice(cortex_3d[i, :, :]))
        if overlay_im is not None and overlay_neo_meso_no_allocortex_3d is not None:
            overlay_im.set_data(_binary_overlay_slice(overlay_neo_meso_no_allocortex_3d[i, :, :]))
        if r_im is not None:
            assert r_um_crop is not None and crop_origin is not None
            zi0, y0, x0 = (int(crop_origin[0]), int(crop_origin[1]), int(crop_origin[2]))
            z = int(i)
            r2 = np.full_like(reference_3d[i, :, :], np.nan, dtype=np.float32)
            if zi0 <= z < zi0 + int(r_um_crop.shape[0]):
                zz = z - zi0
                r2[y0 : y0 + int(r_um_crop.shape[1]), x0 : x0 + int(r_um_crop.shape[2])] = r_um_crop[zz]
                if midline_include_3d is not None:
                    r2[~midline_include_3d[i, :, :]] = np.nan
            r_im.set_data(r2)

        _clear_artist(curve_lc)
        curve_lc = None
        active_path_xy: np.ndarray | None = None
        active_path_t: np.ndarray | None = None
        contour_mask = cortex_3d[i, :, :]
        if midline_include_3d is not None:
            contour_mask = contour_mask & midline_include_3d[i, :, :]
        u2 = _masked_u_slice(u_3d[i, :, :], contour_mask)
        curve_source = "none"
        midline_data = coronal_midline_paths.get(int(i))
        manual_path_yx = manual_coronal_paths.get(int(i))
        if midline_data is not None:
            midline_path_xy, midline_path_t = midline_data
        else:
            midline_path_xy, midline_path_t = None, None
        if (
            midline_path_xy is not None
            and midline_path_t is not None
            and midline_path_xy.shape[0] >= 2
            and midline_path_t.shape[0] == midline_path_xy.shape[0]
        ):
            active_path_xy = midline_path_xy.astype(np.float32, copy=False)
            active_path_t = midline_path_t.astype(np.float32, copy=False)
            curve_lc = _plot_parametrized_curve(
                ax,
                [active_path_xy],
                cmap=U_CURVE_T_CMAP,
                norm=curve_norm,
                linewidth=1.2,
                alpha=BOUNDARY_ALPHA,
                zorder=3,
                t_vertices_by_segment=[active_path_t],
            )
            curve_source = "midline_csv"
        elif manual_path_yx is not None and manual_path_yx.shape[0] >= 2:
            # Manual path arrays are stored as (y, x); LineCollection expects (x, y).
            manual_path_xy = manual_path_yx[:, [1, 0]].astype(np.float32, copy=False)
            active_path_xy = manual_path_xy
            active_path_t = None
            curve_lc = _plot_parametrized_curve(
                ax,
                [manual_path_xy],
                cmap=U_CURVE_T_CMAP,
                norm=curve_norm,
                linewidth=1.2,
                alpha=BOUNDARY_ALPHA,
                zorder=3,
            )
            curve_source = "manual"
        elif np.isfinite(u2).any():
            cont = ax.contour(
                u2,
                levels=[float(CONTOUR_LEVEL)],
                linewidths=0.0,
                alpha=0.0,
            )
            contour_segments = [np.asarray(seg, dtype=np.float32) for seg in cont.allsegs[0]]
            if contour_segments:
                active_path_xy = max(contour_segments, key=_polyline_length_xy)
            active_path_t = None
            _clear_contours(cont)
            curve_lc = _plot_parametrized_curve(
                ax,
                contour_segments,
                cmap=U_CURVE_T_CMAP,
                norm=curve_norm,
                linewidth=1.2,
                alpha=BOUNDARY_ALPHA,
                zorder=3,
            )
            curve_source = "u05"
        else:
            curve_lc = None

        if t_im is not None:
            t2 = t_field_cache.get(int(i))
            if t2 is None:
                if active_path_xy is not None and active_path_xy.shape[0] >= 2:
                    if active_path_t is not None and active_path_t.shape[0] == active_path_xy.shape[0]:
                        t_vertices = active_path_t
                    else:
                        t_vertices = _normalized_arc_t_for_path_xy(active_path_xy)
                    t2 = _t_field_from_path(mask_yx=cortex_3d[i, :, :], path_xy=active_path_xy, t_vertices=t_vertices)
                else:
                    t2 = np.full_like(reference_3d[i, :, :], np.nan, dtype=np.float32)
                t_field_cache[int(i)] = t2
            t_im.set_data(t2)

        t_path_data = coronal_midline_paths.get(int(i))
        if t_path_data is not None:
            t_path_xy, t_path_vals = t_path_data
        else:
            t_path_xy, t_path_vals = None, None
        t_extent = None
        if t_path_xy is not None and t_path_vals is not None and overlay_neo_meso_no_allocortex_3d is not None:
            t_extent = _t_extent_on_path_t_for_mask(t_path_xy, t_path_vals, overlay_neo_meso_no_allocortex_3d[i, :, :])
        t_range_label = _format_t_ranges(coronal_overlap_t_ranges.get(int(i), []))
        if t_path_xy is not None and t_path_vals is not None and t_extent is not None:
            t_start, t_end = t_extent
            p_start = _point_on_path_xy_by_t(t_path_xy, t_path_vals, t_start)
            p_end = _point_on_path_xy_by_t(t_path_xy, t_path_vals, t_end)
            sc_t_start.set_offsets(np.asarray([p_start], dtype=np.float64) if p_start is not None else np.empty((0, 2)))
            sc_t_end.set_offsets(np.asarray([p_end], dtype=np.float64) if p_end is not None else np.empty((0, 2)))
            t_range_label = f"{float(t_start):.3f}-{float(t_end):.3f}"
        else:
            sc_t_start.set_offsets(np.empty((0, 2)))
            sc_t_end.set_offsets(np.empty((0, 2)))

        b0 = np.argwhere(b0_3d[i, :, :])
        b1 = np.argwhere(b1_3d[i, :, :])
        # scatter uses x=k, y=j for coronal slices.
        sc_b0.set_offsets(np.column_stack([b0[:, 1], b0[:, 0]]) if b0.size else np.empty((0, 2)))
        sc_b1.set_offsets(np.column_stack([b1[:, 1], b1[:, 0]]) if b1.size else np.empty((0, 2)))

        ax.set_title(
            f"coronal i={i} | mask_px={int(cortex_3d[i].sum())} | "
            f"u finite={int(np.isfinite(u2).sum())} | curve={curve_source} | contour={CONTOUR_LEVEL:g} | "
            f"neo+meso t={t_range_label}"
        )
        fig.canvas.draw_idle()

    pending_i: int | None = None
    debounce_ms = int(max(0, int(SLIDER_DEBOUNCE_MS)))
    timer_i = fig.canvas.new_timer(interval=max(debounce_ms, 1))
    timer_i.single_shot = True

    def flush_i() -> None:
        nonlocal pending_i
        if pending_i is None:
            return
        next_i = int(pending_i)
        pending_i = None
        set_i(next_i)

    timer_i.add_callback(flush_i)

    def on_slider(v: float) -> None:
        nonlocal pending_i
        pending_i = int(np.rint(v))
        if debounce_ms <= 0:
            flush_i()
            return
        timer_i.stop()
        timer_i.start()

    slider.on_changed(on_slider)
    fig._slider = slider  # type: ignore[attr-defined]
    fig._timer = timer_i  # type: ignore[attr-defined]
    fig._set_i = set_i  # type: ignore[attr-defined]

    set_i(cur_i)
    if show:
        plt.show()
    else:
        plt.close(fig)


if SHOW_FIGURES:
    view_coronal_overlay(show=True)


# %% [markdown]
# ## Phase 3: Sagittal viewer (slice k)

# %%
def view_sagittal_overlay(*, show: bool = True) -> None:
    n_k = int(reference_3d.shape[2])
    cur_k = int(np.clip(int(np.nanmedian(np.where(cortex_3d.any(axis=(0, 1)))[0])), 0, n_k - 1))

    fig, ax = plt.subplots(figsize=(7.7, 7.7))
    plt.subplots_adjust(bottom=0.14)
    t_field_cache: dict[int, np.ndarray] = {}

    img = ax.imshow(
        reference_3d[:, :, cur_k],
        cmap="gray",
        interpolation="nearest",
        vmin=vmin,
        vmax=vmax,
        origin="upper",
        aspect="auto",
    )
    mask_im = ax.imshow(
        _binary_overlay_slice(cortex_3d[:, :, cur_k]),
        cmap=plt.cm.colors.ListedColormap([MASK_COLOR]),
        interpolation="nearest",
        alpha=MASK_ALPHA,
        origin="upper",
        aspect="auto",
        zorder=2,
    )
    mask_im.cmap.set_bad(alpha=0.0)
    overlay_im = None
    if overlay_neo_meso_no_allocortex_3d is not None:
        overlay_im = ax.imshow(
            _binary_overlay_slice(overlay_neo_meso_no_allocortex_3d[:, :, cur_k]),
            cmap=plt.cm.colors.ListedColormap([OVERLAY_NEO_MESO_COLOR]),
            interpolation="nearest",
            alpha=float(OVERLAY_NEO_MESO_ALPHA),
            origin="upper",
            aspect="auto",
            zorder=2.2,
        )
        overlay_im.cmap.set_bad(alpha=0.0)
    t_im = None
    r_im = None
    if bool(SHOW_R_OVERLAY):
        cmap_r = plt.get_cmap("coolwarm").copy()
        cmap_r.set_bad(alpha=0.0)
        r_im = ax.imshow(
            np.full_like(reference_3d[:, :, cur_k], np.nan, dtype=np.float32),
            cmap=cmap_r,
            interpolation="nearest",
            origin="upper",
            aspect="auto",
            vmin=-float(R_CLIP_UM),
            vmax=float(R_CLIP_UM),
            alpha=0.55,
            zorder=2.5,
        )

    curve_lc: LineCollection | None = None
    sc_t_start = ax.scatter([], [], s=88.0, c="#ffff00", marker="*", edgecolors="k", linewidths=0.45, zorder=4.5)
    sc_t_end = ax.scatter([], [], s=88.0, c="#ff0000", marker="*", edgecolors="k", linewidths=0.45, zorder=4.5)
    sc_b0 = ax.scatter([], [], s=3.0, c="#1f77b4", alpha=0.7, linewidths=0.0, zorder=4, label="pial seed")
    sc_b1 = ax.scatter([], [], s=3.0, c="#ff7f0e", alpha=0.7, linewidths=0.0, zorder=4, label="inner seed")
    curve_norm = Normalize(vmin=float(sagittal_t_vmin), vmax=float(sagittal_t_vmax))
    curve_sm = plt.cm.ScalarMappable(norm=curve_norm, cmap=U_CURVE_T_CMAP)
    curve_sm.set_array(np.array([curve_norm.vmin, curve_norm.vmax], dtype=np.float32))
    fig.colorbar(curve_sm, ax=ax, fraction=0.046, pad=0.02, label="t_all")
    if bool(SHOW_T_FIELD):
        cmap_t = plt.get_cmap(T_FIELD_CMAP).copy()
        cmap_t.set_bad(alpha=0.0)
        t_im = ax.imshow(
            np.full_like(reference_3d[:, :, cur_k], np.nan, dtype=np.float32),
            cmap=cmap_t,
            norm=curve_norm,
            interpolation="nearest",
            origin="upper",
            aspect="auto",
            alpha=float(T_FIELD_ALPHA),
            zorder=2.35,
        )

    ax.set_xlabel("j (y)")
    ax.set_ylabel("i (coronal slice)")

    slider_ax = fig.add_axes((0.15, 0.06, 0.7, 0.03))
    slider = Slider(slider_ax, "slice k", 0, n_k - 1, valinit=cur_k, valstep=1)

    def set_k(k: int) -> None:
        nonlocal curve_lc
        k = int(np.clip(int(k), 0, n_k - 1))
        img.set_data(reference_3d[:, :, k])
        mask_im.set_data(_binary_overlay_slice(cortex_3d[:, :, k]))
        if overlay_im is not None and overlay_neo_meso_no_allocortex_3d is not None:
            overlay_im.set_data(_binary_overlay_slice(overlay_neo_meso_no_allocortex_3d[:, :, k]))
        if r_im is not None:
            assert r_um_crop is not None and crop_origin is not None
            z0, y0, x0 = (int(crop_origin[0]), int(crop_origin[1]), int(crop_origin[2]))
            x = int(k)
            r2 = np.full_like(reference_3d[:, :, k], np.nan, dtype=np.float32)
            if x0 <= x < x0 + int(r_um_crop.shape[2]):
                xx = x - x0
                r2[z0 : z0 + int(r_um_crop.shape[0]), y0 : y0 + int(r_um_crop.shape[1])] = r_um_crop[:, :, xx]
                if midline_include_3d is not None:
                    r2[~midline_include_3d[:, :, k]] = np.nan
            r_im.set_data(r2)

        _clear_artist(curve_lc)
        curve_lc = None
        active_path_xy: np.ndarray | None = None
        active_path_t: np.ndarray | None = None
        contour_mask = cortex_3d[:, :, k]
        if midline_include_3d is not None:
            contour_mask = contour_mask & midline_include_3d[:, :, k]
        u2 = _masked_u_slice(u_3d[:, :, k], contour_mask)
        curve_source = "none"
        midline_data = sagittal_midline_paths.get(int(k))
        manual_path_ij = manual_sagittal_paths.get(int(k))
        if midline_data is not None:
            midline_path_xy, midline_path_t = midline_data
        else:
            midline_path_xy, midline_path_t = None, None
        if (
            midline_path_xy is not None
            and midline_path_t is not None
            and midline_path_xy.shape[0] >= 2
            and midline_path_t.shape[0] == midline_path_xy.shape[0]
        ):
            active_path_xy = midline_path_xy.astype(np.float32, copy=False)
            active_path_t = midline_path_t.astype(np.float32, copy=False)
            curve_lc = _plot_parametrized_curve(
                ax,
                [active_path_xy],
                cmap=U_CURVE_T_CMAP,
                norm=curve_norm,
                linewidth=1.0,
                alpha=BOUNDARY_ALPHA,
                zorder=3,
                t_vertices_by_segment=[active_path_t],
            )
            curve_source = "midline_csv"
        elif manual_path_ij is not None and manual_path_ij.shape[0] >= 2:
            # Manual path arrays are stored as (i, j); LineCollection expects (x=j, y=i).
            manual_path_xy = manual_path_ij[:, [1, 0]].astype(np.float32, copy=False)
            active_path_xy = manual_path_xy
            active_path_t = None
            curve_lc = _plot_parametrized_curve(
                ax,
                [manual_path_xy],
                cmap=U_CURVE_T_CMAP,
                norm=curve_norm,
                linewidth=1.0,
                alpha=BOUNDARY_ALPHA,
                zorder=3,
            )
            curve_source = "manual"
        elif np.isfinite(u2).any():
            cont = ax.contour(
                u2,
                levels=[float(CONTOUR_LEVEL)],
                linewidths=0.0,
                alpha=0.0,
            )
            contour_segments = [np.asarray(seg, dtype=np.float32) for seg in cont.allsegs[0]]
            if contour_segments:
                active_path_xy = max(contour_segments, key=_polyline_length_xy)
            active_path_t = None
            _clear_contours(cont)
            curve_lc = _plot_parametrized_curve(
                ax,
                contour_segments,
                cmap=U_CURVE_T_CMAP,
                norm=curve_norm,
                linewidth=1.0,
                alpha=BOUNDARY_ALPHA,
                zorder=3,
            )
            curve_source = "u05"
        else:
            curve_lc = None

        if t_im is not None:
            t2 = t_field_cache.get(int(k))
            if t2 is None:
                if active_path_xy is not None and active_path_xy.shape[0] >= 2:
                    if active_path_t is not None and active_path_t.shape[0] == active_path_xy.shape[0]:
                        t_vertices = active_path_t
                    else:
                        t_vertices = _normalized_arc_t_for_path_xy(active_path_xy)
                    t2 = _t_field_from_path(mask_yx=cortex_3d[:, :, k], path_xy=active_path_xy, t_vertices=t_vertices)
                else:
                    t2 = np.full_like(reference_3d[:, :, k], np.nan, dtype=np.float32)
                t_field_cache[int(k)] = t2
            t_im.set_data(t2)

        t_path_data = sagittal_midline_paths.get(int(k))
        if t_path_data is not None:
            t_path_xy, t_path_vals = t_path_data
        else:
            t_path_xy, t_path_vals = None, None
        t_extent = None
        if t_path_xy is not None and t_path_vals is not None and overlay_neo_meso_no_allocortex_3d is not None:
            t_extent = _t_extent_on_path_t_for_mask(t_path_xy, t_path_vals, overlay_neo_meso_no_allocortex_3d[:, :, k])
        t_range_label = _format_t_ranges(sagittal_overlap_t_ranges.get(int(k), []))
        if t_path_xy is not None and t_path_vals is not None and t_extent is not None:
            t_start, t_end = t_extent
            p_start = _point_on_path_xy_by_t(t_path_xy, t_path_vals, t_start)
            p_end = _point_on_path_xy_by_t(t_path_xy, t_path_vals, t_end)
            sc_t_start.set_offsets(np.asarray([p_start], dtype=np.float64) if p_start is not None else np.empty((0, 2)))
            sc_t_end.set_offsets(np.asarray([p_end], dtype=np.float64) if p_end is not None else np.empty((0, 2)))
            t_range_label = f"{float(t_start):.3f}-{float(t_end):.3f}"
        else:
            sc_t_start.set_offsets(np.empty((0, 2)))
            sc_t_end.set_offsets(np.empty((0, 2)))

        b0 = np.argwhere(b0_3d[:, :, k])
        b1 = np.argwhere(b1_3d[:, :, k])
        # scatter uses x=j, y=i for sagittal slices.
        sc_b0.set_offsets(np.column_stack([b0[:, 1], b0[:, 0]]) if b0.size else np.empty((0, 2)))
        sc_b1.set_offsets(np.column_stack([b1[:, 1], b1[:, 0]]) if b1.size else np.empty((0, 2)))

        ax.set_title(
            f"sagittal k={k} | mask_px={int(cortex_3d[:, :, k].sum())} | "
            f"u finite={int(np.isfinite(u2).sum())} | curve={curve_source} | contour={CONTOUR_LEVEL:g} | "
            f"neo+meso t={t_range_label}"
        )
        fig.canvas.draw_idle()

    pending_k: int | None = None
    debounce_ms = int(max(0, int(SLIDER_DEBOUNCE_MS)))
    timer_k = fig.canvas.new_timer(interval=max(debounce_ms, 1))
    timer_k.single_shot = True

    def flush_k() -> None:
        nonlocal pending_k
        if pending_k is None:
            return
        next_k = int(pending_k)
        pending_k = None
        set_k(next_k)

    timer_k.add_callback(flush_k)

    def on_slider(v: float) -> None:
        nonlocal pending_k
        pending_k = int(np.rint(v))
        if debounce_ms <= 0:
            flush_k()
            return
        timer_k.stop()
        timer_k.start()

    slider.on_changed(on_slider)
    fig._slider = slider  # type: ignore[attr-defined]
    fig._timer = timer_k  # type: ignore[attr-defined]
    fig._set_k = set_k  # type: ignore[attr-defined]

    set_k(cur_k)
    if show:
        plt.show()
    else:
        plt.close(fig)


if SHOW_FIGURES:
    view_sagittal_overlay(show=True)


# %% [markdown]
# ## Summary

# %%
print(f"Viewer notebook loaded. Artifacts: {OUTDIR}")

# %%
