# %% [markdown]
# # 3D cortex mid-surface overlay viewers (DevCCF E15.5)
#
# Interactive slice viewers (coronal and sagittal) for artifacts generated by:
# `ccf/refextract/midsurface_neocortex_mesocortex_allocortex_ccf_3d.py`
#
# Run cells sequentially. Two Matplotlib slider viewers will open:
# - coronal viewer: slice i (axis 0), showing x=k, y=j
# - sagittal viewer: slice k (axis 2), showing x=j, y=i

# %%
from __future__ import annotations

import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from IPython import get_ipython
from matplotlib.collections import LineCollection
from matplotlib.colors import Normalize
from matplotlib.widgets import Slider

# Optional: VS Code interactive Matplotlib backend
ip = get_ipython()
if ip is not None:
    ip.run_line_magic("matplotlib", "widget")

# %% [markdown]
# ## Configuration

# %%
# === EDIT THESE ===

ATLAS_NAME = "kim_dev_mouse_e15-5_lsfm_20um"
OUTDIR = Path("/home/chaichontat/fishtools2/ccf/out/refextract/midsurface_neocortex_mesocortex_allocortex_3d")
BRAINGLOBE_CONFIG_DIR = Path("ccf/out/atlases/.brainglobe_config")

KEEP_LEFT_HEMISPHERE_ONLY = True
DS = 1

SHOW_FIGURES = True
CONTOUR_LEVEL = 0.5
CONTOUR_COLOR = "#d62728"
U_CURVE_T_CMAP = "viridis"
MASK_COLOR = "#2ca02c"
MASK_ALPHA = 0.18
BOUNDARY_ALPHA = 0.85
SLIDER_DEBOUNCE_MS = 40
MANUAL_CONNECT_CORONAL_PATH_TEMPLATE = "manual_coronal_midcurve_override_slice{slice_i}_yx.npy"
MANUAL_CONNECT_SAGITTAL_PATH_TEMPLATE = "manual_sagittal_midcurve_override_slice{slice_k}_yx.npy"

SHOW_R_OVERLAY = True
R_CLIP_UM = 800.0

OUTDIR.mkdir(parents=True, exist_ok=True)


# %% [markdown]
# ## Helpers

# %%
def _resolution_ijk_um(res: object) -> tuple[float, float, float]:
    if isinstance(res, (int, float)):
        r = float(res)
        return (r, r, r)
    if isinstance(res, (tuple, list)) and len(res) == 3 and all(isinstance(v, (int, float)) for v in res):
        return (float(res[0]), float(res[1]), float(res[2]))
    raise ValueError(f"Unsupported atlas.resolution: {res!r}")


def _robust_vmin_vmax(vol_3d: np.ndarray) -> tuple[float, float]:
    sample = vol_3d[::4, ::4, ::4].astype(np.float32, copy=False)
    vmin, vmax = np.percentile(sample, [1, 99]).astype(np.float64)
    if not np.isfinite(vmin) or not np.isfinite(vmax) or float(vmax) <= float(vmin):
        vmin = float(np.nanmin(sample))
        vmax = float(np.nanmax(sample))
        if not np.isfinite(vmin) or not np.isfinite(vmax) or float(vmax) <= float(vmin):
            vmin, vmax = 0.0, 1.0
    return float(vmin), float(vmax)


def _masked_u_slice(u2: np.ndarray, mask2: np.ndarray) -> np.ndarray:
    u2 = u2.astype(np.float32, copy=False)
    mask2 = mask2.astype(bool, copy=False)
    out = np.full(u2.shape, np.nan, dtype=np.float32)
    out[mask2] = u2[mask2]
    return out


def _load_manual_override_paths(outdir: Path, *, axis: str) -> dict[int, np.ndarray]:
    if axis == "coronal":
        prefix = "manual_coronal_midcurve_override_slice"
        pattern = MANUAL_CONNECT_CORONAL_PATH_TEMPLATE.format(slice_i="*")
    elif axis == "sagittal":
        prefix = "manual_sagittal_midcurve_override_slice"
        pattern = MANUAL_CONNECT_SAGITTAL_PATH_TEMPLATE.format(slice_k="*")
    else:
        raise ValueError(f"Unsupported axis={axis!r}")

    out: dict[int, np.ndarray] = {}
    for path in sorted(outdir.glob(pattern)):
        stem = path.stem
        if not stem.startswith(prefix):
            continue
        tail = stem[len(prefix) :]
        if tail.endswith("_yx"):
            tail = tail[: -len("_yx")]
        if not tail.isdigit():
            continue
        arr = np.load(path).astype(np.float32, copy=False)
        if arr.ndim != 2 or arr.shape[1] != 2 or arr.shape[0] < 2:
            continue
        out[int(tail)] = arr
    return out


def _clear_contours(cont: object | None) -> None:
    if cont is None:
        return
    collections = getattr(cont, "collections", None)
    if collections is None:
        return
    for c in list(collections):
        try:
            c.remove()
        except Exception:
            pass


def _clear_artist(artist: object | None) -> None:
    if artist is None:
        return
    remove = getattr(artist, "remove", None)
    if callable(remove):
        remove()


def _plot_parametrized_curve(
    ax: plt.Axes,
    contour_segments: list[np.ndarray],
    *,
    cmap: str,
    norm: Normalize,
    linewidth: float,
    alpha: float,
    zorder: float,
) -> LineCollection | None:
    segments: list[np.ndarray] = []
    t_values: list[np.ndarray] = []
    for path_xy in contour_segments:
        path_xy = np.asarray(path_xy, dtype=np.float32)
        if path_xy.ndim != 2 or path_xy.shape[0] < 2 or path_xy.shape[1] != 2:
            continue
        t_vertices = np.linspace(0.0, 1.0, path_xy.shape[0], dtype=np.float32)
        segments.append(np.stack([path_xy[:-1], path_xy[1:]], axis=1))
        t_values.append(0.5 * (t_vertices[:-1] + t_vertices[1:]))
    if not segments:
        return None

    lc = LineCollection(
        np.concatenate(segments, axis=0),
        cmap=cmap,
        norm=norm,
        linewidths=linewidth,
        alpha=alpha,
        zorder=zorder,
    )
    lc.set_array(np.concatenate(t_values, axis=0))
    ax.add_collection(lc)
    return lc


# %% [markdown]
# ## Phase 0: Load atlas reference

# %%
if BRAINGLOBE_CONFIG_DIR.exists():
    os.environ["BRAINGLOBE_CONFIG_DIR"] = str(BRAINGLOBE_CONFIG_DIR.resolve())

from brainglobe_atlasapi import BrainGlobeAtlas  # noqa: E402

atlas = BrainGlobeAtlas(ATLAS_NAME)
RES_I_UM, RES_J_UM, RES_K_UM = _resolution_ijk_um(atlas.resolution)
print(f"ATLAS_NAME={ATLAS_NAME!r}")
print(f"atlas.resolution={atlas.resolution!r} (um)")

reference_3d = np.asarray(atlas.reference)
reference_3d = reference_3d[::DS, ::DS, ::DS]
if KEEP_LEFT_HEMISPHERE_ONLY:
    reference_3d = reference_3d[:, :, : reference_3d.shape[2] // 2]
print(f"reference_3d (downsampled) shape={reference_3d.shape} dtype={reference_3d.dtype}")


# %% [markdown]
# ## Phase 1: Load midsurface artifacts

# %%
req = {
    "cortex_fit": OUTDIR / "cortex_mask_fit_3d_ds.npy",
    "cortex_clean": OUTDIR / "cortex_mask_clean_3d_ds.npy",
    "u_halfway": OUTDIR / "halfway_u_3d_ds.npy",
    "b0": OUTDIR / "laplace_b0_pial_3d_ds.npy",
    "b1": OUTDIR / "laplace_b1_inner_3d_ds.npy",
    "r_um": OUTDIR / "halfway_r_um_crop.npy",
    "crop_origin": OUTDIR / "halfway_crop_origin_ijk.npy",
    "midline_include": OUTDIR / "midline_include_neo_meso_3d_ds.npy",
}
missing = [name for name in ["b0", "b1"] if not req[name].exists()]
if missing or (not req["cortex_fit"].exists() and not req["cortex_clean"].exists()) or (not req["u_halfway"].exists()):
    raise FileNotFoundError(
        f"Missing artifacts in {OUTDIR}: {missing}. Run midsurface_neocortex_mesocortex_allocortex_ccf_3d.py first."
    )

mask_path = req["cortex_fit"] if req["cortex_fit"].exists() else req["cortex_clean"]
cortex_3d = np.load(mask_path).astype(bool)
u_path = req["u_halfway"]
u_3d = np.load(req["u_halfway"]).astype(np.float32, copy=False)
b0_3d = np.load(req["b0"]).astype(bool)
b1_3d = np.load(req["b1"]).astype(bool)
print(f"Loaded cortex mask: {mask_path}")
print(f"Loaded u field: {u_path}")

midline_include_3d: np.ndarray | None = None
if req["midline_include"].exists():
    midline_include_3d = np.load(req["midline_include"]).astype(bool)
    if midline_include_3d.shape != cortex_3d.shape:
        raise ValueError(
            f"midline_include shape mismatch: {midline_include_3d.shape} vs cortex {cortex_3d.shape} (check DS)."
        )
    print(f"Loaded midline include mask: {req['midline_include']}")

r_um_crop: np.ndarray | None = None
crop_origin: np.ndarray | None = None
if bool(SHOW_R_OVERLAY):
    if not req["r_um"].exists() or not req["crop_origin"].exists():
        raise FileNotFoundError(f"SHOW_R_OVERLAY=True but missing {req['r_um'].name} or {req['crop_origin'].name}")
    r_um_crop = np.load(req["r_um"]).astype(np.float32, copy=False)
    crop_origin = np.load(req["crop_origin"]).astype(np.int32, copy=False)
    if crop_origin.shape != (3,):
        raise ValueError(f"Expected crop_origin shape (3,), got {crop_origin.shape}")
    print(f"Loaded r field: {req['r_um']}")

if KEEP_LEFT_HEMISPHERE_ONLY:
    # Reference is already halved; make sure overlays match.
    kmax = cortex_3d.shape[2]
    reference_3d = reference_3d[:, :, :kmax]

if reference_3d.shape != cortex_3d.shape or cortex_3d.shape != u_3d.shape:
    raise ValueError(
        f"Shape mismatch: reference={reference_3d.shape} cortex={cortex_3d.shape} u={u_3d.shape}. "
        f"Check DS and KEEP_LEFT_HEMISPHERE_ONLY."
    )

vmin, vmax = _robust_vmin_vmax(reference_3d)
manual_coronal_paths = _load_manual_override_paths(OUTDIR, axis="coronal")
manual_sagittal_paths = _load_manual_override_paths(OUTDIR, axis="sagittal")
if manual_coronal_paths:
    print(f"Loaded {len(manual_coronal_paths)} coronal manual override paths from {OUTDIR}")
if manual_sagittal_paths:
    print(f"Loaded {len(manual_sagittal_paths)} sagittal manual override paths from {OUTDIR}")


# %% [markdown]
# ## Phase 2: Coronal viewer (slice i)

# %%
def view_coronal_overlay(*, show: bool = True) -> None:
    n_i = int(reference_3d.shape[0])
    cur_i = int(np.clip(int(np.nanmedian(np.where(cortex_3d.any(axis=(1, 2)))[0])), 0, n_i - 1))

    fig, ax = plt.subplots(figsize=(7.7, 7.7))
    plt.subplots_adjust(bottom=0.14)

    img = ax.imshow(
        reference_3d[cur_i, :, :],
        cmap="gray",
        interpolation="nearest",
        vmin=vmin,
        vmax=vmax,
        origin="upper",
    )
    mask_im = ax.imshow(
        cortex_3d[cur_i, :, :].astype(np.float32),
        cmap=plt.cm.colors.ListedColormap([MASK_COLOR]),
        interpolation="nearest",
        alpha=MASK_ALPHA,
        origin="upper",
        vmin=0.0,
        vmax=1.0,
        zorder=2,
    )
    r_im = None
    if bool(SHOW_R_OVERLAY):
        cmap_r = plt.get_cmap("coolwarm").copy()
        cmap_r.set_bad(alpha=0.0)
        r_im = ax.imshow(
            np.full_like(reference_3d[cur_i, :, :], np.nan, dtype=np.float32),
            cmap=cmap_r,
            interpolation="nearest",
            origin="upper",
            vmin=-float(R_CLIP_UM),
            vmax=float(R_CLIP_UM),
            alpha=0.55,
            zorder=2.5,
        )

    curve_lc: LineCollection | None = None
    sc_b0 = ax.scatter([], [], s=3.0, c="#1f77b4", alpha=0.7, linewidths=0.0, zorder=4, label="pial seed")
    sc_b1 = ax.scatter([], [], s=3.0, c="#ff7f0e", alpha=0.7, linewidths=0.0, zorder=4, label="inner seed")
    curve_norm = Normalize(vmin=0.0, vmax=1.0)
    curve_sm = plt.cm.ScalarMappable(norm=curve_norm, cmap=U_CURVE_T_CMAP)
    curve_sm.set_array(np.array([0.0, 1.0], dtype=np.float32))
    fig.colorbar(curve_sm, ax=ax, fraction=0.046, pad=0.02, label="u-curve t")

    ax.set_xlabel("k (x)")
    ax.set_ylabel("j (y)")

    slider_ax = fig.add_axes((0.15, 0.06, 0.7, 0.03))
    slider = Slider(slider_ax, "slice i", 0, n_i - 1, valinit=cur_i, valstep=1)

    def set_i(i: int) -> None:
        nonlocal curve_lc
        i = int(np.clip(int(i), 0, n_i - 1))
        img.set_data(reference_3d[i, :, :])
        mask_im.set_data(cortex_3d[i, :, :].astype(np.float32, copy=False))
        if r_im is not None:
            assert r_um_crop is not None and crop_origin is not None
            zi0, y0, x0 = (int(crop_origin[0]), int(crop_origin[1]), int(crop_origin[2]))
            z = int(i)
            r2 = np.full_like(reference_3d[i, :, :], np.nan, dtype=np.float32)
            if zi0 <= z < zi0 + int(r_um_crop.shape[0]):
                zz = z - zi0
                r2[y0 : y0 + int(r_um_crop.shape[1]), x0 : x0 + int(r_um_crop.shape[2])] = r_um_crop[zz]
                if midline_include_3d is not None:
                    r2[~midline_include_3d[i, :, :]] = np.nan
            r_im.set_data(r2)

        _clear_artist(curve_lc)
        curve_lc = None
        contour_mask = cortex_3d[i, :, :]
        if midline_include_3d is not None:
            contour_mask = contour_mask & midline_include_3d[i, :, :]
        u2 = _masked_u_slice(u_3d[i, :, :], contour_mask)
        manual_path_yx = manual_coronal_paths.get(int(i))
        if manual_path_yx is not None and manual_path_yx.shape[0] >= 2:
            # Manual path arrays are stored as (y, x); LineCollection expects (x, y).
            manual_path_xy = manual_path_yx[:, [1, 0]].astype(np.float32, copy=False)
            curve_lc = _plot_parametrized_curve(
                ax,
                [manual_path_xy],
                cmap=U_CURVE_T_CMAP,
                norm=curve_norm,
                linewidth=1.2,
                alpha=BOUNDARY_ALPHA,
                zorder=3,
            )
        elif np.isfinite(u2).any():
            cont = ax.contour(
                u2,
                levels=[float(CONTOUR_LEVEL)],
                linewidths=0.0,
                alpha=0.0,
            )
            contour_segments = [np.asarray(seg, dtype=np.float32) for seg in cont.allsegs[0]]
            _clear_contours(cont)
            curve_lc = _plot_parametrized_curve(
                ax,
                contour_segments,
                cmap=U_CURVE_T_CMAP,
                norm=curve_norm,
                linewidth=1.2,
                alpha=BOUNDARY_ALPHA,
                zorder=3,
            )
        else:
            curve_lc = None

        b0 = np.argwhere(b0_3d[i, :, :])
        b1 = np.argwhere(b1_3d[i, :, :])
        # scatter uses x=k, y=j for coronal slices.
        sc_b0.set_offsets(np.column_stack([b0[:, 1], b0[:, 0]]) if b0.size else np.empty((0, 2)))
        sc_b1.set_offsets(np.column_stack([b1[:, 1], b1[:, 0]]) if b1.size else np.empty((0, 2)))

        ax.set_title(
            f"coronal i={i} | mask_px={int(cortex_3d[i].sum())} | "
            f"u finite={int(np.isfinite(u2).sum())} | contour={CONTOUR_LEVEL:g}"
        )
        fig.canvas.draw_idle()

    pending_i: int | None = None
    debounce_ms = int(max(0, int(SLIDER_DEBOUNCE_MS)))
    timer_i = fig.canvas.new_timer(interval=max(debounce_ms, 1))
    timer_i.single_shot = True

    def flush_i() -> None:
        nonlocal pending_i
        if pending_i is None:
            return
        next_i = int(pending_i)
        pending_i = None
        set_i(next_i)

    timer_i.add_callback(flush_i)

    def on_slider(v: float) -> None:
        nonlocal pending_i
        pending_i = int(np.rint(v))
        if debounce_ms <= 0:
            flush_i()
            return
        timer_i.stop()
        timer_i.start()

    slider.on_changed(on_slider)
    fig._slider = slider  # type: ignore[attr-defined]
    fig._timer = timer_i  # type: ignore[attr-defined]
    fig._set_i = set_i  # type: ignore[attr-defined]

    set_i(cur_i)
    if show:
        plt.show()
    else:
        plt.close(fig)


if SHOW_FIGURES:
    view_coronal_overlay(show=True)


# %% [markdown]
# ## Phase 3: Sagittal viewer (slice k)

# %%
def view_sagittal_overlay(*, show: bool = True) -> None:
    n_k = int(reference_3d.shape[2])
    cur_k = int(np.clip(int(np.nanmedian(np.where(cortex_3d.any(axis=(0, 1)))[0])), 0, n_k - 1))

    fig, ax = plt.subplots(figsize=(7.7, 7.7))
    plt.subplots_adjust(bottom=0.14)

    img = ax.imshow(
        reference_3d[:, :, cur_k],
        cmap="gray",
        interpolation="nearest",
        vmin=vmin,
        vmax=vmax,
        origin="upper",
        aspect="auto",
    )
    mask_im = ax.imshow(
        cortex_3d[:, :, cur_k].astype(np.float32),
        cmap=plt.cm.colors.ListedColormap([MASK_COLOR]),
        interpolation="nearest",
        alpha=MASK_ALPHA,
        origin="upper",
        aspect="auto",
        vmin=0.0,
        vmax=1.0,
        zorder=2,
    )
    r_im = None
    if bool(SHOW_R_OVERLAY):
        cmap_r = plt.get_cmap("coolwarm").copy()
        cmap_r.set_bad(alpha=0.0)
        r_im = ax.imshow(
            np.full_like(reference_3d[:, :, cur_k], np.nan, dtype=np.float32),
            cmap=cmap_r,
            interpolation="nearest",
            origin="upper",
            aspect="auto",
            vmin=-float(R_CLIP_UM),
            vmax=float(R_CLIP_UM),
            alpha=0.55,
            zorder=2.5,
        )

    curve_lc: LineCollection | None = None
    sc_b0 = ax.scatter([], [], s=3.0, c="#1f77b4", alpha=0.7, linewidths=0.0, zorder=4, label="pial seed")
    sc_b1 = ax.scatter([], [], s=3.0, c="#ff7f0e", alpha=0.7, linewidths=0.0, zorder=4, label="inner seed")
    curve_norm = Normalize(vmin=0.0, vmax=1.0)
    curve_sm = plt.cm.ScalarMappable(norm=curve_norm, cmap=U_CURVE_T_CMAP)
    curve_sm.set_array(np.array([0.0, 1.0], dtype=np.float32))
    fig.colorbar(curve_sm, ax=ax, fraction=0.046, pad=0.02, label="u-curve t")

    ax.set_xlabel("j (y)")
    ax.set_ylabel("i (coronal slice)")

    slider_ax = fig.add_axes((0.15, 0.06, 0.7, 0.03))
    slider = Slider(slider_ax, "slice k", 0, n_k - 1, valinit=cur_k, valstep=1)

    def set_k(k: int) -> None:
        nonlocal curve_lc
        k = int(np.clip(int(k), 0, n_k - 1))
        img.set_data(reference_3d[:, :, k])
        mask_im.set_data(cortex_3d[:, :, k].astype(np.float32, copy=False))
        if r_im is not None:
            assert r_um_crop is not None and crop_origin is not None
            z0, y0, x0 = (int(crop_origin[0]), int(crop_origin[1]), int(crop_origin[2]))
            x = int(k)
            r2 = np.full_like(reference_3d[:, :, k], np.nan, dtype=np.float32)
            if x0 <= x < x0 + int(r_um_crop.shape[2]):
                xx = x - x0
                r2[z0 : z0 + int(r_um_crop.shape[0]), y0 : y0 + int(r_um_crop.shape[1])] = r_um_crop[:, :, xx]
                if midline_include_3d is not None:
                    r2[~midline_include_3d[:, :, k]] = np.nan
            r_im.set_data(r2)

        _clear_artist(curve_lc)
        curve_lc = None
        contour_mask = cortex_3d[:, :, k]
        if midline_include_3d is not None:
            contour_mask = contour_mask & midline_include_3d[:, :, k]
        u2 = _masked_u_slice(u_3d[:, :, k], contour_mask)
        manual_path_ij = manual_sagittal_paths.get(int(k))
        if manual_path_ij is not None and manual_path_ij.shape[0] >= 2:
            # Manual path arrays are stored as (i, j); LineCollection expects (x=j, y=i).
            manual_path_xy = manual_path_ij[:, [1, 0]].astype(np.float32, copy=False)
            curve_lc = _plot_parametrized_curve(
                ax,
                [manual_path_xy],
                cmap=U_CURVE_T_CMAP,
                norm=curve_norm,
                linewidth=1.0,
                alpha=BOUNDARY_ALPHA,
                zorder=3,
            )
        elif np.isfinite(u2).any():
            cont = ax.contour(
                u2,
                levels=[float(CONTOUR_LEVEL)],
                linewidths=0.0,
                alpha=0.0,
            )
            contour_segments = [np.asarray(seg, dtype=np.float32) for seg in cont.allsegs[0]]
            _clear_contours(cont)
            curve_lc = _plot_parametrized_curve(
                ax,
                contour_segments,
                cmap=U_CURVE_T_CMAP,
                norm=curve_norm,
                linewidth=1.0,
                alpha=BOUNDARY_ALPHA,
                zorder=3,
            )
        else:
            curve_lc = None

        b0 = np.argwhere(b0_3d[:, :, k])
        b1 = np.argwhere(b1_3d[:, :, k])
        # scatter uses x=j, y=i for sagittal slices.
        sc_b0.set_offsets(np.column_stack([b0[:, 1], b0[:, 0]]) if b0.size else np.empty((0, 2)))
        sc_b1.set_offsets(np.column_stack([b1[:, 1], b1[:, 0]]) if b1.size else np.empty((0, 2)))

        ax.set_title(
            f"sagittal k={k} | mask_px={int(cortex_3d[:, :, k].sum())} | "
            f"u finite={int(np.isfinite(u2).sum())} | contour={CONTOUR_LEVEL:g}"
        )
        fig.canvas.draw_idle()

    pending_k: int | None = None
    debounce_ms = int(max(0, int(SLIDER_DEBOUNCE_MS)))
    timer_k = fig.canvas.new_timer(interval=max(debounce_ms, 1))
    timer_k.single_shot = True

    def flush_k() -> None:
        nonlocal pending_k
        if pending_k is None:
            return
        next_k = int(pending_k)
        pending_k = None
        set_k(next_k)

    timer_k.add_callback(flush_k)

    def on_slider(v: float) -> None:
        nonlocal pending_k
        pending_k = int(np.rint(v))
        if debounce_ms <= 0:
            flush_k()
            return
        timer_k.stop()
        timer_k.start()

    slider.on_changed(on_slider)
    fig._slider = slider  # type: ignore[attr-defined]
    fig._timer = timer_k  # type: ignore[attr-defined]
    fig._set_k = set_k  # type: ignore[attr-defined]

    set_k(cur_k)
    if show:
        plt.show()
    else:
        plt.close(fig)


if SHOW_FIGURES:
    view_sagittal_overlay(show=True)


# %% [markdown]
# ## Summary

# %%
print(f"Viewer notebook loaded. Artifacts: {OUTDIR}")
