# %% [markdown]
# # 3D neocortex/mesocortex plotting workflow (DevCCF E15.5)
#
# This file visualizes artifacts generated by
# `ccf/refextract/skeletonize_neocortex_mesocortex_ccf_3d.py`.
#
# Run cells sequentially. QC figures are saved under `OUTDIR`, and optional interactive
# slider views can be enabled from the config cell.

# %%
from __future__ import annotations

import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from IPython import get_ipython
from matplotlib.lines import Line2D
from matplotlib.widgets import Slider
from scipy.ndimage import distance_transform_edt

# Optional: VS Code interactive Matplotlib backend
ip = get_ipython()
if ip is not None:
    ip.run_line_magic("matplotlib", "widget")

# %% [markdown]
# ## Configuration

# %%
# === EDIT THESE ===

ATLAS_NAME = "kim_dev_mouse_e15-5_lsfm_20um"
OUTDIR = Path("ccf/out/refextract/skeletonize_neocortex_mesocortex_3d")
BRAINGLOBE_CONFIG_DIR = Path("ccf/out/atlases/.brainglobe_config")
PLOT_MAX_SKELETON_POINTS = 60_000
MAX_SLICES_TO_PLOT = 150
CHART_MAP_ERR_CLIP_PERCENTILE = 95.0
CHART_MAX_LINES = 80
PLOT_SAGITTAL_LINES_IN_PHASE2 = True
RUN_SAGITTAL_POINTS_IN_CORONAL_SLICE = True
SAGITTAL_POINTS_I_TOL_VOX = 0.5
SHOW_FIGURES = True
RUN_CHART_MAP_QC = True
RUN_CORONAL_3D = True
RUN_V_VIEWERS = True
SLIDER_DEBOUNCE_MS = 40

OUTDIR.mkdir(parents=True, exist_ok=True)


# %% [markdown]
# ## Helpers
#
# Utility and plotting functions used by the phase cells below.

# %%
def _resolution_ijk_um(res: object) -> tuple[float, float, float]:
    if isinstance(res, (int, float)):
        r = float(res)
        return (r, r, r)
    if isinstance(res, (tuple, list)) and len(res) == 3 and all(isinstance(v, (int, float)) for v in res):
        return (float(res[0]), float(res[1]), float(res[2]))
    raise ValueError(f"Unsupported atlas.resolution: {res!r}")


def _robust_vmin_vmax(vol_3d: np.ndarray) -> tuple[float, float]:
    sample = vol_3d[::4, ::4, ::4].astype(np.float32, copy=False)
    vmin, vmax = np.percentile(sample, [1, 99]).astype(np.float64)
    if not np.isfinite(vmin) or not np.isfinite(vmax) or float(vmax) <= float(vmin):
        vmin = float(np.nanmin(sample))
        vmax = float(np.nanmax(sample))
        if not np.isfinite(vmin) or not np.isfinite(vmax) or float(vmax) <= float(vmin):
            vmin, vmax = 0.0, 1.0
    return float(vmin), float(vmax)


def _v_shading_image(
    *,
    shape: tuple[int, int],
    vent_yx: np.ndarray,
    pia_yx: np.ndarray,
    mask_yx: np.ndarray,
    n_v_samples: int = 64,
) -> np.ndarray:
    if vent_yx.shape != pia_yx.shape or vent_yx.ndim != 2 or vent_yx.shape[1] != 2:
        raise ValueError(f"Expected vent/pia shape (N,2), got {vent_yx.shape} and {pia_yx.shape}")
    h, w = int(shape[0]), int(shape[1])
    mask_yx = mask_yx.astype(bool, copy=False)
    if not np.any(mask_yx):
        return np.full((h, w), np.nan, dtype=np.float32)

    def _seed_from_points(points_yx: np.ndarray) -> np.ndarray:
        pts = np.asarray(points_yx, dtype=np.float64)
        finite = np.isfinite(pts).all(axis=1)
        pts = pts[finite]
        if pts.shape[0] == 0:
            return np.zeros((h, w), dtype=bool)
        yi = np.clip(np.rint(pts[:, 0]).astype(np.int32), 0, h - 1)
        xi = np.clip(np.rint(pts[:, 1]).astype(np.int32), 0, w - 1)

        # Snap any out-of-mask points to the nearest in-mask pixel to avoid seeding outside the domain.
        outside = ~mask_yx[yi, xi]
        if np.any(outside):
            _, nearest_idx = distance_transform_edt(~mask_yx, return_distances=True, return_indices=True)
            oy = yi[outside]
            ox = xi[outside]
            yi[outside] = nearest_idx[0, oy, ox].astype(np.int32)
            xi[outside] = nearest_idx[1, oy, ox].astype(np.int32)

        seed = np.zeros((h, w), dtype=bool)
        seed[yi, xi] = True
        return seed

    vent_seed = _seed_from_points(vent_yx)
    pia_seed = _seed_from_points(pia_yx)
    if not np.any(vent_seed) or not np.any(pia_seed):
        return np.full((h, w), np.nan, dtype=np.float32)

    # Robust dense field: v = d(vent) / (d(vent) + d(pia)).
    d_vent = distance_transform_edt(~vent_seed).astype(np.float32, copy=False)
    d_pia = distance_transform_edt(~pia_seed).astype(np.float32, copy=False)
    denom = d_vent + d_pia
    v_img = np.full((h, w), np.nan, dtype=np.float32)
    ok = mask_yx & (denom > 0.0)
    v_img[ok] = (d_vent[ok] / denom[ok]).astype(np.float32, copy=False)
    return v_img


def _load_thickness_by_slice(csv_path: Path) -> dict[int, dict[str, np.ndarray]]:
    table = np.loadtxt(csv_path, delimiter=",", skiprows=1)
    if table.ndim == 1:
        table = table[None, :]
    if table.shape[1] != 11:
        raise ValueError(f"Unexpected columns in {csv_path}: {table.shape}")

    slice_vals = table[:, 0].astype(np.int32)
    u = table[:, 1].astype(np.float64)
    y = table[:, 5].astype(np.float64)
    x = table[:, 6].astype(np.float64)
    vent_y = table[:, 7].astype(np.float64)
    vent_x = table[:, 8].astype(np.float64)
    pia_y = table[:, 9].astype(np.float64)
    pia_x = table[:, 10].astype(np.float64)

    out: dict[int, dict[str, np.ndarray]] = {}
    for slice_idx in np.unique(slice_vals).tolist():
        keep = slice_vals == int(slice_idx)
        out[int(slice_idx)] = {
            "u": u[keep],
            "y": y[keep],
            "x": x[keep],
            "vent_y": vent_y[keep],
            "vent_x": vent_x[keep],
            "pia_y": pia_y[keep],
            "pia_x": pia_x[keep],
        }
    return out


def _set_axes_equal_3d(ax_: object, xyz_um: np.ndarray) -> None:
    mins = np.min(xyz_um, axis=0)
    maxs = np.max(xyz_um, axis=0)
    ctr = (mins + maxs) / 2.0
    half = (maxs - mins) / 2.0
    radius = float(np.max(half))
    if not np.isfinite(radius) or radius <= 0:
        return
    ax_.set_xlim(ctr[0] - radius, ctr[0] + radius)
    ax_.set_ylim(ctr[1] - radius, ctr[1] + radius)
    ax_.set_zlim(ctr[2] - radius, ctr[2] + radius)
    set_box_aspect = getattr(ax_, "set_box_aspect", None)
    if callable(set_box_aspect):
        ax_.set_box_aspect((1, 1, 1))


def view_chart_map_heatmaps(*, clip_err_percentile: float = 95.0, show: bool = True) -> None:
    d = np.load(OUTDIR / "chart_map_coronal_to_sagittal.npz")
    slice_i = d["slice_i"].astype(np.int32, copy=False)
    u_c = d["u_c"].astype(np.float64, copy=False)
    slice_k = d["slice_k"].astype(np.int32, copy=False)
    u_s = d["u_s"].astype(np.float64, copy=False)
    err_um = d["err_um"].astype(np.float64, copy=False)

    finite_err = np.isfinite(err_um)
    if np.any(finite_err):
        med = float(np.nanmedian(err_um))
        p95 = float(np.nanpercentile(err_um, 95))
        mx = float(np.nanmax(err_um))
        print(f"chart_map coronal->sagittal err_um: median={med:.2f}  p95={p95:.2f}  max={mx:.2f}")
        clip = float(np.nanpercentile(err_um, float(clip_err_percentile)))
        if not np.isfinite(clip) or clip <= 0:
            clip = float(p95) if np.isfinite(p95) and p95 > 0 else 1.0
    else:
        clip = 1.0

    err_plot = np.clip(err_um, 0.0, float(clip))
    extent = [float(u_c[0]), float(u_c[-1]), float(slice_i[0]), float(slice_i[-1])]

    fig, axs = plt.subplots(1, 3, figsize=(12.5, 4.0), sharey=True, layout="constrained")
    for ax, z, title, cmap in [
        (axs[0], slice_k.astype(np.float64), "slice_k", "viridis"),
        (axs[1], u_s, "u_s", "turbo"),
        (axs[2], err_plot, f"err_um (clip p{clip_err_percentile:g})", "magma"),
    ]:
        im = ax.imshow(
            z,
            origin="lower",
            aspect="auto",
            extent=extent,
            interpolation="nearest",
            cmap=cmap,
        )
        fig.colorbar(im, ax=ax, shrink=0.85, pad=0.02)
        ax.set_xlabel("u_c")
        ax.set_title(title)
    axs[0].set_ylabel("slice_i")
    fig.savefig(OUTDIR / "chart_map_coronal_to_sagittal_heatmaps.png", dpi=220)
    if show:
        plt.show()
    else:
        plt.close(fig)


def view_sagittal_slices_in_coronal_chart(*, max_lines: int = 80, show: bool = True) -> None:
    d = np.load(OUTDIR / "chart_map_sagittal_to_coronal.npz")
    slice_k = d["slice_k"].astype(np.int32, copy=False)
    u_c = d["u_c"].astype(np.float64, copy=False)
    slice_i = d["slice_i"].astype(np.float64, copy=False)

    if slice_k.ndim != 1 or u_c.ndim != 2 or slice_i.ndim != 2:
        raise ValueError(f"Unexpected shapes: slice_k={slice_k.shape}, u_c={u_c.shape}, slice_i={slice_i.shape}")
    if u_c.shape != slice_i.shape or u_c.shape[0] != slice_k.shape[0]:
        raise ValueError(f"Shape mismatch: slice_k={slice_k.shape}, u_c={u_c.shape}, slice_i={slice_i.shape}")

    stride = int(max(1, int(np.ceil(slice_k.size / max(int(max_lines), 1)))))
    ks = slice_k[::stride]
    cmap = plt.get_cmap("viridis")
    norm = plt.Normalize(vmin=float(np.min(ks)), vmax=float(np.max(ks)))

    fig, ax = plt.subplots(figsize=(6.3, 6.3), layout="constrained")
    for kk in range(0, slice_k.size, stride):
        ok = np.isfinite(u_c[kk]) & np.isfinite(slice_i[kk]) & (slice_i[kk] >= 0.0)
        if not np.any(ok):
            continue
        ax.plot(
            u_c[kk, ok],
            slice_i[kk, ok],
            lw=0.8,
            alpha=0.7,
            c=cmap(norm(float(slice_k[kk]))),
        )

    sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, shrink=0.85, pad=0.02)
    cbar.set_label("slice_k")

    ax.set_xlabel("u_c")
    ax.set_ylabel("slice_i")
    ax.set_title("Sagittal slices (k) embedded in coronal chart")
    fig.savefig(OUTDIR / "chart_map_sagittal_slices_in_coronal_chart.png", dpi=220)
    if show:
        plt.show()
    else:
        plt.close(fig)


def view_coronal_slice_with_sagittal_points(
    *,
    res_i_um: float,
    res_j_um: float,
    res_k_um: float,
    show: bool = True,
    i_tol_vox: float = 0.5,
) -> None:
    """
    Visualize sagittal spline sample points that lie near a coronal plane (slice_i).

    This is useful for diagnosing Phase 1 chart-map discontinuities by inspecting how
    sagittal polylines intersect a fixed coronal section.
    """
    mask_3d = np.load(OUTDIR / "mask_3d.npy").astype(bool)
    reference_3d = np.asarray(atlas.reference)[:, :, : mask_3d.shape[2]]

    spline_csv = OUTDIR / "sagittal_slice_lines_spline_um.csv"
    if not spline_csv.exists():
        raise FileNotFoundError(f"Missing required artifact: {spline_csv}")

    table = np.loadtxt(spline_csv, delimiter=",", skiprows=1)
    if table.ndim == 1:
        table = table[None, :]
    if table.shape[1] != 5:
        raise ValueError(f"Unexpected columns in {spline_csv.name}: {table.shape}")

    slice_k = table[:, 0].astype(np.int32, copy=False)
    i_um = table[:, 2].astype(np.float64, copy=False)
    j_um = table[:, 3].astype(np.float64, copy=False)
    k_um = table[:, 4].astype(np.float64, copy=False)

    n_i = int(mask_3d.shape[0])
    vmin, vmax = _robust_vmin_vmax(reference_3d)
    cur_i = int(np.clip(int(np.nanmedian(i_um / float(res_i_um))), 0, n_i - 1))
    tol_um = float(max(0.0, float(i_tol_vox))) * float(res_i_um)

    cmap = plt.get_cmap("viridis")
    norm = plt.Normalize(vmin=float(np.min(slice_k)), vmax=float(np.max(slice_k)))

    fig, ax = plt.subplots(figsize=(7.5, 7.5))
    plt.subplots_adjust(bottom=0.14)
    img = ax.imshow(
        reference_3d[cur_i, :, :],
        cmap="gray",
        interpolation="nearest",
        vmin=vmin,
        vmax=vmax,
        origin="upper",
    )

    def points_for_i(i: int) -> tuple[np.ndarray, np.ndarray]:
        i = int(np.clip(int(i), 0, n_i - 1))
        keep = np.isfinite(i_um) & np.isfinite(j_um) & np.isfinite(k_um) & (np.abs(i_um - float(i) * res_i_um) <= tol_um)
        if not np.any(keep):
            return np.empty((0, 2), dtype=np.float64), np.empty((0,), dtype=np.float64)
        j_idx = j_um[keep] / float(res_j_um)
        k_idx = k_um[keep] / float(res_k_um)
        pts = np.column_stack([k_idx, j_idx]).astype(np.float64, copy=False)
        return pts, slice_k[keep].astype(np.float64, copy=False)

    pts0, c0 = points_for_i(cur_i)
    sc = ax.scatter(
        pts0[:, 0],
        pts0[:, 1],
        s=6.0,
        c=c0,
        cmap=cmap,
        norm=norm,
        alpha=0.65,
        linewidths=0.0,
    )

    ax.set_xlabel("k (x)")
    ax.set_ylabel("j (y)")
    cbar = fig.colorbar(sc, ax=ax, pad=0.02, fraction=0.04)
    cbar.set_label("slice_k")

    slider_ax = fig.add_axes((0.15, 0.06, 0.7, 0.03))
    slider = Slider(slider_ax, "slice i", 0, n_i - 1, valinit=cur_i, valstep=1)

    def set_i(i: int) -> None:
        i = int(np.clip(int(i), 0, n_i - 1))
        img.set_data(reference_3d[i, :, :])
        pts, cvals = points_for_i(i)
        sc.set_offsets(pts)
        sc.set_array(cvals)
        ax.set_title(f"coronal i={i} | sagittal spline pts={int(pts.shape[0])} | |i-i*|<= {tol_um:.2f} um")
        fig.canvas.draw_idle()

    pending_i: int | None = None
    debounce_ms = int(max(0, int(SLIDER_DEBOUNCE_MS)))
    timer_i = fig.canvas.new_timer(interval=max(debounce_ms, 1))
    timer_i.single_shot = True

    def flush_i() -> None:
        nonlocal pending_i
        if pending_i is None:
            return
        next_i = int(pending_i)
        pending_i = None
        set_i(next_i)

    timer_i.add_callback(flush_i)

    def on_slider(v: float) -> None:
        nonlocal pending_i
        pending_i = int(np.rint(v))
        if debounce_ms <= 0:
            flush_i()
            return
        timer_i.stop()
        timer_i.start()

    slider.on_changed(on_slider)
    fig._slider = slider  # type: ignore[attr-defined]
    fig._on_slider = on_slider  # type: ignore[attr-defined]
    fig._timer = timer_i  # type: ignore[attr-defined]
    fig._flush = flush_i  # type: ignore[attr-defined]
    fig._set_i = set_i  # type: ignore[attr-defined]

    set_i(cur_i)
    fig.savefig(OUTDIR / "coronal_slice_with_sagittal_points.png", dpi=220)
    if show:
        plt.show()
    else:
        plt.close(fig)


def view_v_parameterization_coronal(
    *,
    mask_3d: np.ndarray,
    background_3d: np.ndarray,
    thickness_by_slice: dict[int, dict[str, np.ndarray]],
) -> None:
    n_i = int(mask_3d.shape[0])
    background_3d = background_3d[:, :, : mask_3d.shape[2]]
    vmin, vmax = _robust_vmin_vmax(background_3d)

    slices = sorted(thickness_by_slice.keys())
    if not slices:
        raise ValueError("thickness_by_slice is empty.")
    cur_i = int(np.clip(int(np.median(slices)), 0, n_i - 1))

    cmap = plt.get_cmap("turbo").copy()
    cmap.set_bad(alpha=0.0)

    fig, ax = plt.subplots(figsize=(7.5, 7.5))
    plt.subplots_adjust(bottom=0.14)

    img = ax.imshow(
        background_3d[cur_i, :, :],
        cmap="gray",
        interpolation="nearest",
        vmin=vmin,
        vmax=vmax,
    )
    v_im = ax.imshow(
        np.full_like(background_3d[cur_i, :, :], np.nan, dtype=np.float32),
        cmap=cmap,
        interpolation="nearest",
        vmin=0.0,
        vmax=1.0,
        alpha=0.65,
        zorder=2,
    )
    (spline_line,) = ax.plot([], [], c="white", lw=1.0, alpha=0.9)
    ax.set_xlabel("x (k)")
    ax.set_ylabel("y (j)")
    cbar = fig.colorbar(v_im, ax=ax, pad=0.02, fraction=0.04)
    cbar.set_label("v (ventricular=0 -> pial=1)")

    slider_ax = fig.add_axes((0.15, 0.06, 0.7, 0.03))
    slider = Slider(slider_ax, "slice i", 0, n_i - 1, valinit=cur_i, valstep=1)

    cache: dict[int, np.ndarray] = {}
    cache_order: list[int] = []

    def v_for_slice(i: int) -> np.ndarray:
        if i in cache:
            return cache[i]
        meas = thickness_by_slice.get(i)
        if meas is None:
            return np.full(mask_3d.shape[1:], np.nan, dtype=np.float32)
        vent = np.column_stack([meas["vent_y"], meas["vent_x"]]).astype(np.float64)
        pia = np.column_stack([meas["pia_y"], meas["pia_x"]]).astype(np.float64)
        finite = np.isfinite(vent).all(axis=1) & np.isfinite(pia).all(axis=1)
        mask_yx = mask_3d[i, :, :].astype(bool, copy=False)
        out = _v_shading_image(shape=mask_yx.shape, vent_yx=vent[finite], pia_yx=pia[finite], mask_yx=mask_yx)
        cache[i] = out
        cache_order.append(i)
        if len(cache_order) > 12:
            drop = cache_order.pop(0)
            cache.pop(drop, None)
        return out

    def set_i(i: int) -> None:
        i = int(np.clip(i, 0, n_i - 1))
        img.set_data(background_3d[i, :, :])
        v_im.set_data(v_for_slice(i))
        meas = thickness_by_slice.get(i)
        if meas is None:
            spline_line.set_data([], [])
            n_pts = 0
        else:
            spline_line.set_data(meas["x"], meas["y"])
            n_pts = int(meas["x"].shape[0])
        ax.set_title(f"coronal i={i}  |  u_samples={n_pts}  |  mask_px={int(mask_3d[i].sum())}")
        fig.canvas.draw_idle()

    pending_i: int | None = None
    debounce_ms = int(max(0, int(SLIDER_DEBOUNCE_MS)))
    timer_i = fig.canvas.new_timer(interval=max(debounce_ms, 1))
    timer_i.single_shot = True

    def flush_i() -> None:
        nonlocal pending_i
        if pending_i is None:
            return
        next_i = int(pending_i)
        pending_i = None
        set_i(next_i)

    timer_i.add_callback(flush_i)

    def on_slider(v: float) -> None:
        nonlocal pending_i
        pending_i = int(np.rint(v))
        if debounce_ms <= 0:
            flush_i()
            return
        timer_i.stop()
        timer_i.start()

    slider.on_changed(on_slider)
    fig._slider = slider  # type: ignore[attr-defined]
    fig._on_slider = on_slider  # type: ignore[attr-defined]
    fig._timer = timer_i  # type: ignore[attr-defined]
    fig._flush = flush_i  # type: ignore[attr-defined]
    fig._set_i = set_i  # type: ignore[attr-defined]
    set_i(cur_i)
    plt.show()


def view_v_parameterization_sagittal(
    *,
    mask_3d: np.ndarray,
    background_3d: np.ndarray,
    thickness_by_slice: dict[int, dict[str, np.ndarray]],
) -> None:
    n_k = int(mask_3d.shape[2])
    background_3d = background_3d[:, :, : mask_3d.shape[2]]
    vmin, vmax = _robust_vmin_vmax(background_3d)
    slices = sorted(thickness_by_slice.keys())
    if not slices:
        raise ValueError("thickness_by_slice is empty.")
    cur_k = int(np.clip(int(np.median(slices)), 0, n_k - 1))

    cmap = plt.get_cmap("turbo").copy()
    cmap.set_bad(alpha=0.0)

    fig, ax = plt.subplots(figsize=(7.5, 7.5))
    plt.subplots_adjust(bottom=0.14)

    img = ax.imshow(
        background_3d[:, :, cur_k],
        cmap="gray",
        interpolation="nearest",
        vmin=vmin,
        vmax=vmax,
        aspect="auto",
    )
    v_im = ax.imshow(
        np.full_like(background_3d[:, :, cur_k], np.nan, dtype=np.float32),
        cmap=cmap,
        interpolation="nearest",
        vmin=0.0,
        vmax=1.0,
        alpha=0.65,
        aspect="auto",
        zorder=2,
    )
    (spline_line,) = ax.plot([], [], c="white", lw=1.0, alpha=0.9)
    ax.set_xlabel("y (j)")
    ax.set_ylabel("coronal slice (i)")
    cbar = fig.colorbar(v_im, ax=ax, pad=0.02, fraction=0.04)
    cbar.set_label("v (ventricular=0 -> pial=1)")

    slider_ax = fig.add_axes((0.15, 0.06, 0.7, 0.03))
    slider = Slider(slider_ax, "x (k)", 0, n_k - 1, valinit=cur_k, valstep=1)

    cache: dict[int, np.ndarray] = {}
    cache_order: list[int] = []

    def v_for_slice(k: int) -> np.ndarray:
        if k in cache:
            return cache[k]
        meas = thickness_by_slice.get(k)
        if meas is None:
            return np.full(mask_3d.shape[:2], np.nan, dtype=np.float32)
        vent = np.column_stack([meas["vent_y"], meas["vent_x"]]).astype(np.float64)
        pia = np.column_stack([meas["pia_y"], meas["pia_x"]]).astype(np.float64)
        finite = np.isfinite(vent).all(axis=1) & np.isfinite(pia).all(axis=1)
        mask_ij = mask_3d[:, :, k].astype(bool, copy=False)
        out = _v_shading_image(shape=mask_ij.shape, vent_yx=vent[finite], pia_yx=pia[finite], mask_yx=mask_ij)
        cache[k] = out
        cache_order.append(k)
        if len(cache_order) > 12:
            drop = cache_order.pop(0)
            cache.pop(drop, None)
        return out

    def set_k(k: int) -> None:
        k = int(np.clip(k, 0, n_k - 1))
        img.set_data(background_3d[:, :, k])
        v_im.set_data(v_for_slice(k))
        meas = thickness_by_slice.get(k)
        if meas is None:
            spline_line.set_data([], [])
            n_pts = 0
        else:
            spline_line.set_data(meas["x"], meas["y"])
            n_pts = int(meas["x"].shape[0])
        ax.set_title(f"sagittal k={k}  |  u_samples={n_pts}  |  mask_px={int(mask_3d[:, :, k].sum())}")
        fig.canvas.draw_idle()

    pending_k: int | None = None
    debounce_ms = int(max(0, int(SLIDER_DEBOUNCE_MS)))
    timer_k = fig.canvas.new_timer(interval=max(debounce_ms, 1))
    timer_k.single_shot = True

    def flush_k() -> None:
        nonlocal pending_k
        if pending_k is None:
            return
        next_k = int(pending_k)
        pending_k = None
        set_k(next_k)

    timer_k.add_callback(flush_k)

    def on_slider(v: float) -> None:
        nonlocal pending_k
        pending_k = int(np.rint(v))
        if debounce_ms <= 0:
            flush_k()
            return
        timer_k.stop()
        timer_k.start()

    slider.on_changed(on_slider)
    fig._slider = slider  # type: ignore[attr-defined]
    fig._on_slider = on_slider  # type: ignore[attr-defined]
    fig._timer = timer_k  # type: ignore[attr-defined]
    fig._flush = flush_k  # type: ignore[attr-defined]
    fig._set_k = set_k  # type: ignore[attr-defined]
    set_k(cur_k)
    plt.show()


def plot_coronal_lines_3d(
    *,
    res_i_um: float,
    res_j_um: float,
    res_k_um: float,
    include_sagittal: bool = True,
    show: bool = True,
) -> None:
    def load_lines(csv_path: Path) -> list[np.ndarray]:
        table = np.loadtxt(csv_path, delimiter=",", skiprows=1)
        if table.ndim == 1:
            table = table[None, :]
        if table.shape[1] != 5:
            raise ValueError(f"Unexpected columns in {csv_path.name}: {table.shape}")
        slice_ids = table[:, 0].astype(np.int32, copy=False)
        xyz_um = table[:, 2:5].astype(np.float64, copy=False)
        out: list[np.ndarray] = []
        for slice_idx in np.unique(slice_ids).tolist():
            out.append(xyz_um[slice_ids == int(slice_idx)])
        return out

    coronal_lines_um = load_lines(OUTDIR / "coronal_slice_lines_um.csv")
    sagittal_lines_um: list[np.ndarray] = []
    sagittal_csv = OUTDIR / "sagittal_slice_lines_um.csv"
    if bool(include_sagittal) and sagittal_csv.exists():
        sagittal_lines_um = load_lines(sagittal_csv)

    lines_to_plot = coronal_lines_um
    if len(lines_to_plot) > int(MAX_SLICES_TO_PLOT):
        pick = np.linspace(0, len(lines_to_plot) - 1, int(MAX_SLICES_TO_PLOT)).astype(np.int64)
        lines_to_plot = [lines_to_plot[int(p)] for p in pick.tolist()]

    sagittal_to_plot = sagittal_lines_um
    if len(sagittal_to_plot) > int(MAX_SLICES_TO_PLOT):
        pick = np.linspace(0, len(sagittal_to_plot) - 1, int(MAX_SLICES_TO_PLOT)).astype(np.int64)
        sagittal_to_plot = [sagittal_to_plot[int(p)] for p in pick.tolist()]

    skel_ijk = np.column_stack(np.nonzero(np.load(OUTDIR / "skeleton_3d.npy").astype(bool))).astype(np.float64)
    if skel_ijk.shape[0] > PLOT_MAX_SKELETON_POINTS:
        idx = np.linspace(0, skel_ijk.shape[0] - 1, PLOT_MAX_SKELETON_POINTS).astype(np.int64)
        skel_ijk = skel_ijk[idx]
    skel_um = np.column_stack([skel_ijk[:, 0] * res_i_um, skel_ijk[:, 1] * res_j_um, skel_ijk[:, 2] * res_k_um])

    fig = plt.figure(figsize=(11, 8))
    ax = fig.add_subplot(111, projection="3d")
    ax.scatter(skel_um[:, 0], skel_um[:, 1], skel_um[:, 2], s=0.25, c="dimgray", alpha=0.18, linewidths=0)

    coronal_k_medians_um = [float(np.median(path_um[:, 2])) for path_um in lines_to_plot]
    sagittal_k_medians_um = [float(np.median(path_um[:, 2])) for path_um in sagittal_to_plot]

    if len(lines_to_plot) <= 1 and not sagittal_to_plot:
        coronal_colors = ["cyan"] * len(lines_to_plot)
        sagittal_colors = []
    else:
        # Anchor the colormap normalization to the coronal set so the color direction/scale
        # is stable when sagittal overlays are toggled on/off.
        k_for_norm = np.asarray(
            coronal_k_medians_um if coronal_k_medians_um else sagittal_k_medians_um,
            dtype=np.float64,
        )
        if k_for_norm.size == 0:
            coronal_colors = ["cyan"] * len(lines_to_plot)
            sagittal_colors = ["cyan"] * len(sagittal_to_plot)
        else:
            k0, k1 = np.nanpercentile(k_for_norm, [1, 99])
            if not np.isfinite(k0) or not np.isfinite(k1) or float(k1) <= float(k0):
                k0 = float(np.nanmin(k_for_norm))
                k1 = float(np.nanmax(k_for_norm))
                if not np.isfinite(k0) or not np.isfinite(k1):
                    k0, k1 = 0.0, 1.0
                elif float(k1) <= float(k0):
                    k1 = k0 + 1.0

            cmap = plt.get_cmap("viridis")
            norm = plt.Normalize(vmin=float(k0), vmax=float(k1))
            coronal_colors = [cmap(norm(k)) for k in coronal_k_medians_um]
            sagittal_colors = [cmap(norm(k)) for k in sagittal_k_medians_um]

            sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
            sm.set_array([])
            cbar = fig.colorbar(sm, ax=ax, pad=0.02, fraction=0.04)
            cbar.set_label("median k (um)")

    for path_um, color in zip(lines_to_plot, coronal_colors, strict=True):
        ax.plot(path_um[:, 0], path_um[:, 1], path_um[:, 2], c=color, lw=1.0, alpha=0.9)

    if sagittal_to_plot:
        for path_um, color in zip(sagittal_to_plot, sagittal_colors, strict=True):
            ax.plot(path_um[:, 0], path_um[:, 1], path_um[:, 2], c=color, lw=0.9, alpha=0.55, ls="--")

    ax.legend(
        handles=[
            Line2D([0], [0], c="0.2", lw=1.2, alpha=0.9, label="coronal lines"),
            Line2D([0], [0], c="0.2", lw=1.0, alpha=0.6, ls="--", label="sagittal lines"),
        ],
        loc="upper left",
        frameon=True,
    )

    ax.set_xlabel("i_um")
    ax.set_ylabel("j_um")
    ax.set_zlabel("k_um")
    ax.set_title(
        f"{ATLAS_NAME} | coronal lines={len(coronal_lines_um)} (plotted {len(lines_to_plot)})"
        + (f" | sagittal lines={len(sagittal_lines_um)} (plotted {len(sagittal_to_plot)})" if sagittal_lines_um else "")
    )
    _set_axes_equal_3d(ax, skel_um)
    ax.view_init(elev=23, azim=40)
    fig.tight_layout()
    fig.savefig(OUTDIR / "mpl3d_coronal_slice_lines.png", dpi=220)
    if show:
        plt.show()
    else:
        plt.close(fig)


# %% [markdown]
# ## Phase 0: Load atlas metadata

# %%
if BRAINGLOBE_CONFIG_DIR.exists():
    os.environ["BRAINGLOBE_CONFIG_DIR"] = str(BRAINGLOBE_CONFIG_DIR.resolve())

from brainglobe_atlasapi import BrainGlobeAtlas  # noqa: E402

atlas = BrainGlobeAtlas(ATLAS_NAME)
RES_I_UM, RES_J_UM, RES_K_UM = _resolution_ijk_um(atlas.resolution)
print(f"ATLAS_NAME={ATLAS_NAME!r}")
print(f"atlas.resolution={atlas.resolution!r} (um)")


# %% [markdown]
# ## Phase 1: Chart-map QC plots

# %%
if RUN_CHART_MAP_QC:
    view_chart_map_heatmaps(clip_err_percentile=float(CHART_MAP_ERR_CLIP_PERCENTILE), show=bool(SHOW_FIGURES))
    view_sagittal_slices_in_coronal_chart(max_lines=int(CHART_MAX_LINES), show=bool(SHOW_FIGURES))
else:
    print("RUN_CHART_MAP_QC=False (skipping chart-map QC plots).")

# %% [markdown]
# ## Phase 1b: Coronal slice view with sagittal points
#
# Shows a single coronal slice (atlas reference) with overlaid points sampled from sagittal spline
# polylines that lie near that coronal plane.

# %%
if RUN_SAGITTAL_POINTS_IN_CORONAL_SLICE:
    spline_csv = OUTDIR / "sagittal_slice_lines_spline_um.csv"
    if not spline_csv.exists():
        print(f"Skipping Phase 1b (missing {spline_csv}; generate via skeletonize_neocortex_mesocortex_ccf_3d.py).")
    else:
        view_coronal_slice_with_sagittal_points(
            res_i_um=float(RES_I_UM),
            res_j_um=float(RES_J_UM),
            res_k_um=float(RES_K_UM),
            i_tol_vox=float(SAGITTAL_POINTS_I_TOL_VOX),
            show=bool(SHOW_FIGURES),
        )
else:
    print("RUN_SAGITTAL_POINTS_IN_CORONAL_SLICE=False (skipping coronal slice sagittal-point view).")


# %% [markdown]
# ## Phase 2: Coronal lines 3D plot

# %%
if RUN_CORONAL_3D:
    plot_coronal_lines_3d(
        res_i_um=float(RES_I_UM),
        res_j_um=float(RES_J_UM),
        res_k_um=float(RES_K_UM),
        include_sagittal=bool(PLOT_SAGITTAL_LINES_IN_PHASE2),
        show=bool(SHOW_FIGURES),
    )
else:
    print("RUN_CORONAL_3D=False (skipping 3D coronal line plot).")


# %% [markdown]
# ## Phase 3: Optional interactive v-parameter viewers
#
# Uses thickness CSV artifacts from generation:
# - `coronal_spline_thickness.csv`
# - `sagittal_spline_thickness.csv`

# %%
if RUN_V_VIEWERS:
    mask_3d = np.load(OUTDIR / "mask_3d.npy").astype(bool)
    neo_meso_3d = np.load(OUTDIR / "neo_meso_3d.npy").astype(bool)
    reference_3d = np.asarray(atlas.reference)[:, :, : mask_3d.shape[2]]
    mask_neo_meso_3d = (mask_3d & neo_meso_3d).astype(bool)
    thickness_by_slice_i = _load_thickness_by_slice(OUTDIR / "coronal_spline_thickness.csv")
    thickness_by_slice_k = _load_thickness_by_slice(OUTDIR / "sagittal_spline_thickness.csv")
    view_v_parameterization_coronal(
        mask_3d=mask_neo_meso_3d,
        background_3d=reference_3d,
        thickness_by_slice=thickness_by_slice_i,
    )
    view_v_parameterization_sagittal(
        mask_3d=mask_neo_meso_3d,
        background_3d=reference_3d,
        thickness_by_slice=thickness_by_slice_k,
    )
else:
    print("RUN_V_VIEWERS=False (skipping interactive v-parameter viewers).")


# %% [markdown]
# ## Summary
#
# Saved outputs include:
# - `chart_map_coronal_to_sagittal_heatmaps.png`
# - `chart_map_sagittal_slices_in_coronal_chart.png`
# - `mpl3d_coronal_slice_lines.png`

# %%
print(f"Plotting workflow complete. Outputs are under: {OUTDIR}")
