name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          pip install .
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py310 .
      - name: Test
        run: |
          wget https://libd-spatial-dlpfc-loopy.s3.amazonaws.com/VisiumIF/sample.tif
          tojxl .
          tojxl . --quality=100 --delete
          todax .
          if [ ! -f sample.dax ]; then exit 1; fi
