name: Install and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: fishtools
          environment-file: environment.yml
          python-version: 3.12
          conda-remove-defaults: true

      - name: Install dependencies
        run: pip install .[dev]

      - name: Test
        run: pytest
